import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { adminToken, authenticatedAdminRequest } from "../public/admin/admin-session.js";

function storage(values={}){const data=new Map(Object.entries(values));return {getItem:key=>data.get(key)||null,setItem:(key,value)=>data.set(key,value),removeItem:key=>data.delete(key),has:key=>data.has(key)};}

test("unlocked Product Centre authorizes Customer Finder refresh through the canonical session",async()=>{const session=storage({bingoAdminCoreToken:"admin-token"});let request;await authenticatedAdminRequest(async(url,options)=>{request={url,options};return new Response("{}")},session,"/api/admin/prospecting");assert.equal(adminToken(session),"admin-token");assert.equal(request.url,"/api/admin/prospecting");assert.equal(request.options.headers.Authorization,"Bearer admin-token");});

test("unlocked Product Centre manual run carries the same authorization",async()=>{const session=storage({bingoAdminGiftCardToken:"legacy-admin-token"});let request;await authenticatedAdminRequest(async(url,options)=>{request={url,options};return new Response("{}")},session,"/api/admin/prospecting/run",{method:"POST",body:"{}"});assert.equal(request.options.method,"POST");assert.equal(request.options.headers.Authorization,"Bearer legacy-admin-token");});

test("locked Product Centre never makes a prospecting status request",async()=>{const session=storage();let requests=0;let locked=false;await assert.rejects(()=>authenticatedAdminRequest(async()=>{requests+=1;return new Response("{}")},session,"/api/admin/prospecting",{},()=>{locked=true}),/locked/);assert.equal(requests,0);assert.equal(locked,true);});

test("expired or invalid token clears the canonical session and returns to safe locked state",async()=>{const session=storage({bingoAdminCoreToken:"expired",bingoAdminGiftCardToken:"fallback"});let locked=false;await assert.rejects(()=>authenticatedAdminRequest(async()=>new Response("{}",{status:401}),session,"/api/admin/prospecting",{},()=>{locked=true}),/expired/);assert.equal(adminToken(session),"");assert.equal(locked,true);});

test("Customer Finder refresh and manual run both use the canonical authenticated request",()=>{const source=readFileSync(new URL("../public/admin/ai-drafts.js",import.meta.url),"utf8");const refresh=source.slice(source.indexOf("async function loadProspecting"),source.indexOf("function renderProspecting"));const manual=source.slice(source.indexOf("async function runProspectingManually"),source.indexOf("function clearWorkspace"));assert.match(refresh,/adminRequest\(`\$\{prospectingApi\}\?\$\{params\}`\)/);assert.match(manual,/adminRequest\(`\$\{prospectingApi\}\/run`/);assert.doesNotMatch(refresh,/\bfetch\(/);assert.doesNotMatch(manual,/\bfetch\(/);});

test("Customer Finder surfaces sanitized Places reason, classification, and invalid field",()=>{const source=readFileSync(new URL("../public/admin/ai-drafts.js",import.meta.url),"utf8");const formatter=source.slice(source.indexOf("function prospectingFailureMessage"),source.indexOf("async function runProspectingManually"));assert.match(formatter,/providerErrors/);assert.match(formatter,/first\.reason/);assert.match(formatter,/first\.classification/);assert.match(formatter,/first\.invalidFields/);assert.doesNotMatch(formatter,/error_description|rawResponse|GOOGLE_PLACES_API_KEY/);});

test("Customer Finder renders a non-null Google Place ID beneath the existing source",()=>{const source=readFileSync(new URL("../public/admin/ai-drafts.js",import.meta.url),"utf8");const details=source.slice(source.indexOf("function prospectSourceDetails"),source.indexOf("function prospectRow"));const renderer=source.slice(source.indexOf("function prospectRow"),source.indexOf("async function prospectingAction"));assert.match(details,/const details=\[p\.source\]/);assert.match(details,/p\.google_place_id/);assert.match(details,/`Place ID: \$\{String\(p\.google_place_id\)\.trim\(\)\}`/);assert.match(renderer,/p\.email\|\|"No public email",prospectSourceDetails\(p\)/);});

test("Customer Finder omits absent Place IDs and preserves compliance controls",()=>{const source=readFileSync(new URL("../public/admin/ai-drafts.js",import.meta.url),"utf8");const details=source.slice(source.indexOf("function prospectSourceDetails"),source.indexOf("function prospectRow"));const renderer=source.slice(source.indexOf("function prospectRow"),source.indexOf("async function prospectingAction"));assert.match(details,/if\(String\(p\.google_place_id\|\|""\)\.trim\(\)\)/);assert.match(renderer,/p\.business_name,p\.domain/);assert.match(renderer,/p\.business_type,p\.location/);assert.match(renderer,/p\.compliance_status/);assert.match(renderer,/p\.subscriber_type==="corporate"/);assert.match(renderer,/p\.pecr_status==="individual_soft_opt_in_valid"/);assert.match(renderer,/p\.subscriber_type==="unknown"/);assert.match(renderer,/p\.compliance_status!=="eligible"/);assert.match(renderer,/p\.message_status!=="approved"\|\|!state\.prospectingSendingEnabled/);});

test("Customer Finder Phase 2 submits bounded manual Google controls without changing safety actions",()=>{const source=readFileSync(new URL("../public/admin/ai-drafts.js",import.meta.url),"utf8");const html=readFileSync(new URL("../public/admin/ai-drafts.html",import.meta.url),"utf8");const request=source.slice(source.indexOf("function manualProspectingRequest"),source.indexOf("function updateProspectingSummary"));assert.match(request,/location:/);assert.match(request,/categories:/);assert.match(request,/budget:/);assert.match(request,/maxProspects:/);for(const value of ["Maidstone","Kent","London","South East England","United Kingdom"])assert.match(html,new RegExp(`>${value}<`));for(const category of ["dog groomer","pet shop","dog walker","kennel","dog daycare","pet hotel","veterinary clinic","animal charity"])assert.match(html,new RegExp(`value="${category}"`));assert.match(source,/Results remain draft-only and require compliance review and human approval/);assert.match(source,/!state\.prospectingSendingEnabled/);});

test("Customer Finder result filters are display-only",()=>{const source=readFileSync(new URL("../public/admin/ai-drafts.js",import.meta.url),"utf8");const filters=source.slice(source.indexOf("function renderProspectingRows"),source.indexOf("function tableEmpty"));assert.match(filters,/state\.prospects\.filter/);assert.doesNotMatch(filters,/adminRequest|fetch|prospectingAction/);});

test("unlock starts Customer Finder loading before nonessential renderers can fail",()=>{const source=readFileSync(new URL("../public/admin/ai-drafts.js",import.meta.url),"utf8");const unlock=source.slice(source.indexOf("async function unlock"),source.indexOf("const googleMerchantResult"));assert.ok(unlock.indexOf("loadProspecting()")<unlock.indexOf("renderContentCards"));assert.match(unlock,/Promise\.allSettled\(protectedLoads\)/);});
