import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { handleProspectingRequest, prospectingTestHelpers, runProspecting } from "../_functions_NOT_FOR_STATIC_UPLOAD/api/prospecting.js";

const {findCandidates,normaliseGooglePlace,normaliseBusinessType,normaliseProspect,upsertProspect,GOOGLE_FIELD_MASK}=prospectingTestHelpers;
const baseEnv=(overrides={})=>({GOOGLE_PLACES_API_KEY:"test-only",AI_PROSPECTING_SEARCH_TERMS:"dog groomer",AI_PROSPECTING_SEARCH_LOCATIONS:"Maidstone",AI_PROSPECTING_MAX_SEARCHES:"10",AI_PROSPECTING_MAX_GOOGLE_RESULTS:"20",AI_PROSPECTING_RESULTS_PER_SEARCH:"10",GOOGLE_PLACES_ESTIMATED_COST_GBP:"0.03",...overrides});
const place=(overrides={})=>({id:"place-1",displayName:{text:"Maidstone Dog Groomers"},formattedAddress:"1 High Street, Maidstone, Kent",primaryType:"pet_groomer",types:["pet_groomer"],businessStatus:"OPERATIONAL",websiteUri:"https://groomers.example/",googleMapsUri:"https://maps.google.com/?cid=1",location:{latitude:51.27,longitude:0.52},...overrides});

async function mockedDiscovery(env,places,{status=200,malformed=false}={}){const calls=[];const original=globalThis.fetch;globalThis.fetch=async(url,options={})=>{calls.push({url:String(url),options});if(String(url).includes("places.googleapis.com")){if(malformed)return new Response("{",{status,headers:{"Content-Type":"application/json"}});return Response.json({places},{status});}return new Response("<html></html>",{status:200,headers:{"Content-Type":"text/html"}});};try{return {result:await findCandidates(env,Number(env.AI_PROSPECTING_MAX_COST_GBP||1)),calls};}finally{globalThis.fetch=original;}}

test("Maidstone targeting uses Places Text Search New and the minimal explicit field mask",async()=>{const {result,calls}=await mockedDiscovery(baseEnv(),[place()]);const google=calls.find(call=>call.url.includes("places.googleapis.com"));assert.equal(google.url,"https://places.googleapis.com/v1/places:searchText");assert.equal(google.options.headers["X-Goog-FieldMask"],GOOGLE_FIELD_MASK);assert.equal(google.options.headers["X-Goog-FieldMask"].includes("*"),false);assert.equal(JSON.parse(google.options.body).textQuery,"dog groomer in Maidstone");assert.equal(result.diagnostics.searchesAttempted,1);});

test("coordinate configuration adds a bounded radius bias without a separate Nearby request",async()=>{const env=baseEnv({AI_PROSPECTING_SEARCH_LOCATIONS_JSON:JSON.stringify([{name:"Maidstone",latitude:51.27,longitude:0.52,radius:12000}])});const {calls}=await mockedDiscovery(env,[place()]);const body=JSON.parse(calls.find(call=>call.url.includes("places.googleapis.com")).options.body);assert.deepEqual(body.locationBias.circle,{center:{latitude:51.27,longitude:0.52},radius:12000});assert.equal(calls.filter(call=>call.url.includes("places.googleapis.com")).length,1);});

test("configured business categories map deterministically",()=>{const expected=new Map([["dog groomer","dog groomer"],["pet shop","pet shop"],["dog walker","dog walker"],["kennel","kennel"],["dog daycare","dog daycare"],["pet hotel","pet hotel"],["veterinary","veterinary clinic"],["animal charity","animal charity"]]);for(const [term,type] of expected)assert.equal(normaliseBusinessType(term,[]),type);});

test("Google response normalization retains Place ID, website, location and provenance",()=>{const candidate=normaliseGooglePlace(place(),"dog groomer","Maidstone");assert.equal(candidate.google_place_id,"place-1");assert.equal(candidate.website,"https://groomers.example/");assert.equal(candidate.location,"1 High Street, Maidstone, Kent");assert.equal(candidate.source,"google_places");assert.match(candidate.evidence,/Place ID place-1/);assert.match(candidate.evidence,/Maidstone/);});

test("website enrichment preserves Google discovery provenance",async()=>{const original=globalThis.fetch;globalThis.fetch=async url=>String(url).includes("places.googleapis.com")?Response.json({places:[place()]}):new Response("Contact info@groomers.example",{headers:{"Content-Type":"text/html"}});try{const result=await findCandidates(baseEnv(),1);assert.equal(result.candidates[0].source,"google_places");assert.equal(result.candidates[0].source_url,"https://maps.google.com/?cid=1");assert.equal(result.candidates[0].email,"info@groomers.example");assert.match(result.candidates[0].evidence,/generic public email/);}finally{globalThis.fetch=original;}});

test("duplicate Google Place IDs are rejected across overlapping searches",async()=>{const env=baseEnv({AI_PROSPECTING_SEARCH_TERMS:"dog groomer,pet groomer"});const {result}=await mockedDiscovery(env,[place()]);assert.equal(result.candidates.length,1);assert.equal(result.diagnostics.googleResults,2);assert.equal(result.diagnostics.duplicatesRejected,1);});

test("duplicate domains at the same address are rejected",async()=>{const places=[place(),place({id:"place-2",displayName:{text:"Maidstone Grooming Centre"},googleMapsUri:"https://maps.google.com/?cid=2"})];const {result}=await mockedDiscovery(baseEnv(),places);assert.equal(result.candidates.length,1);assert.equal(result.diagnostics.duplicatesRejected,1);});

test("same brand at different legitimate branch addresses remains separate",async()=>{const places=[place(),place({id:"place-2",formattedAddress:"2 High Street, London",googleMapsUri:"https://maps.google.com/?cid=2"})];const {result}=await mockedDiscovery(baseEnv(),places);assert.equal(result.candidates.length,2);assert.equal(result.diagnostics.duplicatesRejected,0);});

test("permanently closed businesses are rejected",async()=>{const {result}=await mockedDiscovery(baseEnv(),[place({businessStatus:"CLOSED_PERMANENTLY"})]);assert.equal(result.candidates.length,0);assert.equal(result.diagnostics.invalidRejected,1);});

test("temporarily closed and missing-status businesses are conservatively rejected",async()=>{const missing=place({id:"place-2"});delete missing.businessStatus;const {result}=await mockedDiscovery(baseEnv(),[place({businessStatus:"CLOSED_TEMPORARILY"}),missing]);assert.equal(result.candidates.length,0);assert.equal(result.diagnostics.invalidRejected,2);});

test("a business without a website remains discoverable but has no email permission",async()=>{const {result}=await mockedDiscovery(baseEnv(),[place({websiteUri:undefined})]);assert.equal(result.candidates.length,1);assert.equal(result.candidates[0].website,"");assert.equal(result.candidates[0].email,"");assert.equal(result.candidates[0].lia_basis_recorded,false);});

test("missing Place IDs fall back to name and address deduplication",async()=>{const withoutId=place({id:undefined});const duplicate=place({id:"  ",googleMapsUri:"https://maps.google.com/?cid=other"});const {result}=await mockedDiscovery(baseEnv(),[withoutId,duplicate]);assert.equal(result.candidates.length,1);assert.equal(result.candidates[0].google_place_id,null);assert.equal(result.diagnostics.duplicatesRejected,1);});

test("migration makes Place ID nullable and uniquely indexes only real IDs",()=>{const sql=readFileSync(new URL("../migrations/0021_google_discovery_phase_1.sql",import.meta.url),"utf8");assert.match(sql,/ADD COLUMN google_place_id TEXT;/);assert.doesNotMatch(sql,/google_place_id TEXT NOT NULL|DEFAULT\s+''/);assert.match(sql,/WHERE google_place_id IS NOT NULL AND trim\(google_place_id\) <> ''/);for(const column of ["google_searches_attempted","google_searches_completed","google_duplicates_rejected","google_invalid_rejected"])assert.match(sql,new RegExp(`${column} INTEGER NOT NULL DEFAULT 0`));});

test("non-Google and missing-ID Google prospects normalize Place ID to NULL",()=>{const now="2026-08-22T00:00:00.000Z";const nonGoogle=normaliseProspect({business_name:"Historic Groomer",business_type:"dog groomer",source:"business_website",source_url:"https://historic.example"},now);const google=normaliseProspect(normaliseGooglePlace(place({id:"  "}),"dog groomer","Maidstone"),now);assert.equal(nonGoogle.google_place_id,null);assert.equal(google.google_place_id,null);});

test("a valid Google Place ID survives prospect normalization",()=>{const prospect=normaliseProspect(normaliseGooglePlace(place(),"dog groomer","Maidstone"),"2026-08-22T00:00:00.000Z");assert.equal(prospect.google_place_id,"place-1");});

test("malformed Google responses are isolated and recorded",async()=>{const {result}=await mockedDiscovery(baseEnv(),[],{malformed:true});assert.equal(result.candidates.length,0);assert.match(result.diagnostics.providerErrors[0],/malformed_json/);});

test("Google API failures are isolated and recorded without candidates",async()=>{const {result}=await mockedDiscovery(baseEnv(),[],{status:503});assert.equal(result.candidates.length,0);assert.match(result.diagnostics.providerErrors[0],/http_503/);});

test("budget exhaustion stops before an unaffordable Google request and marks partial",async()=>{const env=baseEnv({AI_PROSPECTING_MAX_COST_GBP:"0.02"});const {result,calls}=await mockedDiscovery(env,[place()]);assert.equal(calls.length,0);assert.equal(result.cost,0);assert.equal(result.partial,true);assert.equal(result.diagnostics.searchesAttempted,0);});

test("maximum search count stops the geographic plan cleanly",async()=>{const env=baseEnv({AI_PROSPECTING_SEARCH_LOCATIONS:"Maidstone,Kent,London",AI_PROSPECTING_MAX_SEARCHES:"2"});const {result,calls}=await mockedDiscovery(env,[]);assert.equal(calls.length,2);assert.equal(result.diagnostics.searchesCompleted,2);assert.equal(result.partial,true);});

test("maximum returned-business limit truncates results and marks partial",async()=>{const env=baseEnv({AI_PROSPECTING_MAX_GOOGLE_RESULTS:"1"});const {result}=await mockedDiscovery(env,[place(),place({id:"place-2",formattedAddress:"2 High Street, London",googleMapsUri:"https://maps.google.com/?cid=2"})]);assert.equal(result.candidates.length,1);assert.equal(result.partial,true);});

function recordingDb(){const calls=[];return {calls,prepare(sql){let values=[];return {bind(...next){values=next;return this;},async first(){calls.push({sql,values,type:"first"});return null;},async all(){calls.push({sql,values,type:"all"});return {results:[]};},async run(){calls.push({sql,values,type:"run"});return {success:true,meta:{changes:1}};}};}};}
function reconciliationDb({exact=[],historical=[],dedupe=null}={}){const calls=[];const exactRows=[...exact];return {calls,prepare(sql){let values=[];return {bind(...next){values=next;return this;},async first(){calls.push({sql,values,type:"first"});if(sql.includes("WHERE google_place_id=?"))return exactRows.shift()||null;if(sql.includes("WHERE dedupe_key=?"))return dedupe;return null;},async all(){calls.push({sql,values,type:"all"});return {results:historical};},async run(){calls.push({sql,values,type:"run"});return {success:true,meta:{changes:sql.includes("ON CONFLICT DO NOTHING")?0:1}};}};}};}
const historical=(overrides={})=>({id:"historic-1",dedupe_key:"historic-key",business_name:"Maidstone Dog Groomers",location:"1 High Street, Maidstone, Kent",domain:"groomers.example",email:"old@groomers.example",website:"https://groomers.example/",google_place_id:null,subscriber_type:"corporate",lia_basis_recorded:1,consent_recorded:0,compliance_status:"eligible",status:"reviewed",...overrides});
const googleProspect=()=>normaliseProspect(normaliseGooglePlace(place(),"dog groomer","Maidstone"),"2026-08-22T00:00:00.000Z");

test("historical domain and address match is reconciled without losing compliance history",async()=>{const old=historical({business_name:"Different Trading Name"});const db=reconciliationDb({historical:[old]});const resolved=await upsertProspect(db,googleProspect(),"2026-08-22T00:00:00.000Z");assert.equal(resolved.id,old.id);assert.equal(resolved.lia_basis_recorded,true);assert.equal(resolved.subscriber_type,"corporate");const update=db.calls.find(call=>call.type==="run"&&call.sql.startsWith("UPDATE prospects SET business_name"));assert.ok(update);assert.equal(update.values.includes("place-1"),true);assert.doesNotMatch(update.sql,/compliance_status|status=|lia_basis_recorded|consent_recorded|last_contacted_at/);});

test("historical name and address match is reconciled without requiring a domain",async()=>{const old=historical({domain:"",website:""});const candidate=googleProspect();candidate.domain="different.example";const db=reconciliationDb({historical:[old]});const resolved=await upsertProspect(db,candidate,"2026-08-22T00:00:00.000Z");assert.equal(resolved.id,old.id);});

test("ambiguous historical identity is not automatically merged",async()=>{const db=reconciliationDb({historical:[historical(),historical({id:"historic-2",dedupe_key:"historic-key-2"})]});const candidate=googleProspect();await upsertProspect(db,candidate,"2026-08-22T00:00:00.000Z");assert.ok(db.calls.some(call=>call.type==="run"&&call.sql.includes("INSERT INTO prospects")));assert.equal(db.calls.some(call=>call.type==="run"&&call.sql.startsWith("UPDATE prospects SET business_name")),false);});

test("same brand at a different address is not historically reconciled",async()=>{const db=reconciliationDb({historical:[historical({location:"99 Other Road, London",domain:""})]});await upsertProspect(db,googleProspect(),"2026-08-22T00:00:00.000Z");assert.ok(db.calls.some(call=>call.type==="run"&&call.sql.includes("INSERT INTO prospects")));});

test("an exact Place-ID conflict resolves to the existing prospect safely",async()=>{const old=historical({google_place_id:"place-1"});const db=reconciliationDb({exact:[null,old]});const resolved=await upsertProspect(db,googleProspect(),"2026-08-22T00:00:00.000Z");assert.equal(resolved.id,old.id);assert.ok(db.calls.some(call=>call.type==="run"&&call.sql.includes("ON CONFLICT DO NOTHING")));assert.ok(db.calls.some(call=>call.type==="run"&&call.sql.startsWith("UPDATE prospects SET business_name")));});

test("dashboard API tolerates a NULL Google Place ID",async()=>{const db={prepare(sql){let values=[];return {bind(...next){values=next;return this;},async all(){return {results:[{id:"historic-1",business_name:"Historic Groomer",google_place_id:null}]};},async first(){return {id:"run-1",google_searches_completed:0,google_searches_attempted:0,raw_results:0,normalized_results:0,google_duplicates_rejected:0,google_invalid_rejected:0,search_api_cost:0,partial:0};}};}};const response=await handleProspectingRequest(new Request("https://admin.bingodogwash.com/api/admin/prospecting",{headers:{Authorization:"Bearer admin-token"}}),{ADMIN_API_TOKEN:"admin-token",GIFT_CARD_DB:db});assert.equal(response.status,200);assert.equal((await response.json()).prospects[0].google_place_id,null);});
const product={id:"towel-1",name:"Professional Dog Grooming Towel",category:"Dog grooming",description:"Absorbent drying towel for coat care",source:"avasam",url:"https://bingodogwash.com/product.html?id=towel-1",availability:"in stock"};

test("Google discovery feeds product matching and persists an eligible-score match",async()=>{const candidate=normaliseGooglePlace(place(),"dog groomer","Maidstone");const db=recordingDb();const result=await runProspecting({GIFT_CARD_DB:db,AI_PROSPECTING_MIN_SCORE:"55",AI_PROSPECTING_MAX_COST_GBP:"1"},{trigger:"manual",now:"2026-08-20T10:00:00.000Z",candidates:[candidate],products:[product]});assert.equal(result.prospectsFound,1);assert.ok(db.calls.some(call=>call.type==="run"&&call.sql.includes("prospect_product_matches")));});

test("compliance blocking retains a Google product match and creates no draft or approval",async()=>{const candidate=normaliseGooglePlace(place({websiteUri:undefined}),"dog groomer","Maidstone");const db=recordingDb();await runProspecting({GIFT_CARD_DB:db,AI_PROSPECTING_MIN_SCORE:"55",AI_EMAIL_SENDING_ENABLED:"false"},{trigger:"manual",now:"2026-08-21T10:00:00.000Z",candidates:[candidate],products:[product]});assert.ok(db.calls.some(call=>call.type==="run"&&call.sql.includes("prospect_product_matches")));assert.equal(db.calls.some(call=>call.type==="run"&&call.sql.includes("INSERT INTO outreach_messages")),false);assert.equal(db.calls.some(call=>call.values.includes("approved")||call.sql.includes("lia_basis_recorded=1")),false);});
