import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { handleBrevoWebhook, handleProspectingRequest, purgeExpiredProspects, runProspecting, runProspectingSchedule, prospectingTestHelpers } from "../_functions_NOT_FOR_STATIC_UPLOAD/api/prospecting.js";
import worker from "../_functions_NOT_FOR_STATIC_UPLOAD/api/worker.js";

const auth={Authorization:"Bearer admin-token","Content-Type":"application/json"};
const req=(path="",options={})=>new Request(`https://admin.bingodogwash.com/api/admin/prospecting${path}`,{headers:{...auth,...options.headers},...options});

function recordingDb(options={}){const calls=[];return {calls,prepare(sql){let values=[];return {bind(...next){values=next;return this;},async first(){calls.push({sql,values,type:"first"});if(sql.includes("outreach_runs WHERE idempotency_key"))return options.existingRun||null;if(sql.includes("outreach_messages o JOIN prospects"))return options.message||null;if(sql.includes("SELECT email,domain,subscriber_type,subscriber_type_evidence"))return options.prospect||null;if(sql.includes("suppression_list")){const blocked=options.suppressionSequence?.length?options.suppressionSequence.shift():options.suppressed;return blocked?{blocked:1}:null;}return null;},async all(){calls.push({sql,values,type:"all"});return {results:[]};},async run(){calls.push({sql,values,type:"run"});return {success:true,meta:{changes:options.changes??1}};}};}};}
async function withPublicPages(pages,assertion){const oldFetch=globalThis.fetch;const calls=[];globalThis.fetch=async(input)=>{const url=String(input);calls.push(url);const path=new URL(url).pathname;const fixture=pages[url]||pages[path]||{};const page=typeof fixture==="string"?{body:fixture}:fixture;return new Response(page.body||"",{status:page.status||200,headers:{"Content-Type":"text/html; charset=utf-8",...(page.headers||{})}});};try{return await assertion(calls);}finally{globalThis.fetch=oldFetch;}}

test("prospecting endpoints require admin authorisation",async()=>{const response=await handleProspectingRequest(new Request("https://admin.bingodogwash.com/api/admin/prospecting"),{ADMIN_API_TOKEN:"admin-token"});assert.equal(response.status,401);});

test("manual prospecting is independently blocked while its feature flag is false",async()=>{const response=await handleProspectingRequest(req("/run",{method:"POST",body:"{}"}),{ADMIN_API_TOKEN:"admin-token",GIFT_CARD_DB:recordingDb(),AI_PROSPECTING_ENABLED:"false",AI_MANUAL_PROSPECTING_ENABLED:"false"});assert.equal(response.status,409);});

async function manualCatalogueRequest(body,loadProducts){const db=recordingDb();const oldFetch=globalThis.fetch;globalThis.fetch=async()=>Response.json({places:[{id:"manual-place",displayName:{text:"Example Dog Groomer"},formattedAddress:"London",primaryType:"pet_groomer",types:["pet_groomer"],businessStatus:"OPERATIONAL",googleMapsUri:"https://maps.google.com/example"}]});try{const input={location:"London",categories:["dog groomer"],budget:0.09,maxProspects:5,...body};const response=await handleProspectingRequest(req("/run",{method:"POST",body:JSON.stringify(input)}),{ADMIN_API_TOKEN:"admin-token",GIFT_CARD_DB:db,AI_PROSPECTING_ENABLED:"false",AI_MANUAL_PROSPECTING_ENABLED:"true",AI_EMAIL_SENDING_ENABLED:"false",GOOGLE_PLACES_API_KEY:"test-key",AI_PROSPECTING_SEARCH_TERMS:"dog groomer",AI_PROSPECTING_SEARCH_LOCATIONS:"London",AI_PROSPECTING_MIN_SCORE:"55",AI_PROSPECTING_MAX_COST_GBP:"0.25"},undefined,{loadProducts});return {response,db};}finally{globalThis.fetch=oldFetch;}}
test("manual request uses a non-empty submitted product catalogue",async()=>{let loads=0;const {response,db}=await manualCatalogueRequest({products:[matchProduct()]},async()=>{loads+=1;throw new Error("loader must not run");});assert.equal(response.status,200);assert.equal(loads,0);assert.ok(db.calls.some(call=>call.sql.includes("prospect_product_matches")&&call.type==="run"));});
test("manual request with an empty product array loads the canonical catalogue",async()=>{let loads=0;const {response,db}=await manualCatalogueRequest({products:[]},async()=>{loads+=1;return [matchProduct()];});assert.equal(response.status,200);assert.equal(loads,1);assert.ok(db.calls.some(call=>call.sql.includes("prospect_product_matches")&&call.type==="run"));});
test("manual request without products loads the canonical catalogue",async()=>{let loads=0;const {response,db}=await manualCatalogueRequest({},async()=>{loads+=1;return [matchProduct()];});assert.equal(response.status,200);assert.equal(loads,1);assert.ok(db.calls.some(call=>call.sql.includes("prospect_product_matches")&&call.type==="run"));});
test("manual request with invalid products loads the canonical catalogue",async()=>{let loads=0;const {response,db}=await manualCatalogueRequest({products:[null,"invalid"]},async()=>{loads+=1;return [matchProduct()];});assert.equal(response.status,200);assert.equal(loads,1);assert.ok(db.calls.some(call=>call.sql.includes("prospect_product_matches")&&call.type==="run"));});

test("manual discovery controls accept approved presets and conservative custom locations",()=>{const validate=prospectingTestHelpers.manualPreferences;const env={AI_PROSPECTING_MAX_COST_GBP:"0.25",AI_PROSPECTING_MAX_PROSPECTS:"20"};for(const location of ["Maidstone","Kent","London","South East England","United Kingdom","King's Lynn, Norfolk"]){const result=validate({location,categories:["dog groomer","pet shop"],budget:0.09,maxProspects:10},env);assert.equal(result.ok,true);assert.equal(result.value.location,location);assert.equal(result.value.manualGoogle,true);}});
test("manual discovery controls reject arbitrary categories, unsafe locations and server-cap bypasses",()=>{const validate=prospectingTestHelpers.manualPreferences;const env={AI_PROSPECTING_MAX_COST_GBP:"0.15",AI_PROSPECTING_MAX_PROSPECTS:"10"};assert.equal(validate({location:"London",categories:[],budget:0.03,maxProspects:5},env).ok,false);assert.equal(validate({location:"London",categories:["accountant"],budget:0.03,maxProspects:5},env).ok,false);assert.equal(validate({location:"London<script>",categories:["dog groomer"],budget:0.03,maxProspects:5},env).ok,false);assert.equal(validate({location:{city:"London"},categories:["dog groomer"],budget:0.03,maxProspects:5},env).ok,false);assert.equal(validate({location:"London",categories:["dog groomer"],budget:"0.03",maxProspects:5},env).ok,false);assert.equal(validate({location:"London",categories:["dog groomer"],budget:0.25,maxProspects:5},env).ok,false);assert.equal(validate({location:"London",categories:["dog groomer"],budget:0.03,maxProspects:100},env).ok,false);});
test("manual discovery remains available without enabling the nightly schedule",async()=>{const {response}=await manualCatalogueRequest({products:[matchProduct()]},async()=>[]);assert.equal(response.status,200);});

test("PECR decisions are independent from LIA and unknown fails closed",()=>{const pecr=prospectingTestHelpers.pecrDecision;assert.equal(pecr({subscriber_type:"corporate"}),"corporate_no_pecr_consent_required");assert.equal(pecr({subscriber_type:"individual"}),"individual_consent_required");assert.equal(pecr({subscriber_type:"individual",consent_recorded:true}),"individual_consent_valid");assert.equal(pecr({subscriber_type:"individual",soft_opt_in_recorded:true}),"individual_soft_opt_in_valid");assert.equal(pecr({subscriber_type:"unknown"}),"unknown_treated_as_individual");});
test("subscriber type and LIA gates fail closed",()=>{const gate=prospectingTestHelpers.complianceFor;assert.equal(gate({email:"info@limited.test",subscriber_type:"corporate",lia_basis_recorded:false,lia_status:"not_recorded"}),"lia_required");assert.equal(gate({email:"info@limited.test",subscriber_type:"corporate",lia_basis_recorded:true,lia_status:"failed"}),"lia_failed");assert.equal(gate({email:"owner@sole.test",subscriber_type:"individual",lia_basis_recorded:true,lia_status:"passed",consent_recorded:false}),"pecr_consent_required");assert.equal(gate({email:"hello@unknown.test",subscriber_type:"unknown",lia_basis_recorded:true,lia_status:"passed",consent_recorded:false}),"pecr_consent_required");assert.equal(gate({email:"info@limited.test",subscriber_type:"corporate",lia_basis_recorded:true,lia_status:"passed"}),"eligible");assert.equal(gate({email:"owner@sole.test",subscriber_type:"individual",consent_recorded:true}),"eligible");assert.equal(gate({email:"owner@sole.test",subscriber_type:"individual",soft_opt_in_recorded:true,lia_basis_recorded:false,lia_status:"not_recorded"}),"lia_required");assert.equal(gate({email:"owner@sole.test",subscriber_type:"individual",soft_opt_in_recorded:true,lia_basis_recorded:true,lia_status:"passed"}),"eligible");});

test("public website discovery accepts a published custom mailbox without guessing",async()=>{const oldFetch=globalThis.fetch;globalThis.fetch=async()=>new Response("<html><body>Contact jucridor@gmail.com</body></html>",{headers:{"Content-Type":"text/html"}});try{assert.equal(await prospectingTestHelpers.publicBusinessEmail("https://www.jucridor.co.uk/"),"jucridor@gmail.com");}finally{globalThis.fetch=oldFetch;}});
test("public website discovery never invents an address",async()=>{const oldFetch=globalThis.fetch;globalThis.fetch=async()=>new Response("<html><body>Contact us through this form.</body></html>",{headers:{"Content-Type":"text/html"}});try{assert.equal(await prospectingTestHelpers.publicBusinessEmail("https://example.test/"),"");}finally{globalThis.fetch=oldFetch;}});
test("automated no-reply mailboxes are excluded while a later public mailbox is retained",async()=>{const oldFetch=globalThis.fetch;globalThis.fetch=async()=>new Response("<html><body>noreply@example.test owner@example.test</body></html>",{headers:{"Content-Type":"text/html"}});try{assert.equal(await prospectingTestHelpers.publicBusinessEmail("https://example.test/"),"owner@example.test");}finally{globalThis.fetch=oldFetch;}});
test("first-party discovery finds a public Contact-page email and records exact provenance",async()=>withPublicPages({"/":"<a href=\"/contact.html\">Contact us</a>","/contact.html":"<p>Email: bestinshowmaidstone@gmail.com</p>"},async()=>{const result=await prospectingTestHelpers.inspectBusinessWebsite("http://www.bestinshowmaidstone.co.uk/","dog groomer");assert.equal(result.website_verified,true);assert.equal(result.email,"bestinshowmaidstone@gmail.com");assert.equal(result.email_source_url,"http://www.bestinshowmaidstone.co.uk/contact.html");assert.equal(result.email_source_type,"first_party_website");}));
test("first-party discovery accepts relative and absolute www-equivalent Contact links once",async()=>withPublicPages({"/":"<a href=\"/contact.html\">Contact</a><a href=\"https://www.example.test/contact.html\" title=\"Get in touch\">Duplicate</a>","/contact.html":"<a href=\"mailto:hello@example.test\">Email us</a>"},async(calls)=>{const result=await prospectingTestHelpers.inspectBusinessWebsite("https://example.test/","dog groomer");assert.equal(result.email,"hello@example.test");assert.equal(calls.filter(url=>new URL(url).pathname==="/contact.html").length,1);}));
test("public mailto, visible text and simple public obfuscation are normalised without rejecting Gmail",()=>{const emails=prospectingTestHelpers.extractPublicEmails("<a href=\"mailto:BestInShowMaidstone@gmail.com?subject=Hello\">Email</a><p>office@example.test</p><p>name [at] example [dot] com</p>");assert.deepEqual(emails,["bestinshowmaidstone@gmail.com","office@example.test","name@example.com"]);});
const bestInShowCfEmail="1d7f786e6974736e75726a707c74796e697273785d7a707c7471337e7270";
const noreplyCfEmail="422c2d3027322e3b02273a232f322e276c36273136";
test("Cloudflare data-cfemail decodes a valid published mailbox",()=>{assert.equal(prospectingTestHelpers.decodeCfEmail(bestInShowCfEmail),"bestinshowmaidstone@gmail.com");});
test("Best In Show Contact markup discovers the Cloudflare-protected Gmail address with exact provenance",async()=>withPublicPages({"/":"<a href=\"/contact.html\">Contact</a>","/contact.html":`<a href=\"/cdn-cgi/l/email-protection\" class=\"__cf_email__\" data-cfemail=\"${bestInShowCfEmail}\">[email&#160;protected]</a>`},async()=>{const result=await prospectingTestHelpers.inspectBusinessWebsite("http://www.bestinshowmaidstone.co.uk/","dog groomer");assert.equal(result.website_verified,true);assert.equal(result.email,"bestinshowmaidstone@gmail.com");assert.equal(result.email_source_url,"http://www.bestinshowmaidstone.co.uk/contact.html");assert.equal(result.email_source_type,"first_party_website");}));
test("Cloudflare-decoded addresses use the normal no-reply filter",()=>{const markup=`<a href=\"/cdn-cgi/l/email-protection\" class=\"__cf_email__\" data-cfemail=\"${noreplyCfEmail}\">[email&#160;protected]</a>`;assert.deepEqual(prospectingTestHelpers.extractPublicEmails(markup),[]);});
test("Cloudflare data-cfemail rejects invalid hexadecimal values",()=>{assert.equal(prospectingTestHelpers.decodeCfEmail("this-is-not-hex"),"");});
test("Cloudflare data-cfemail rejects odd-length values",()=>{assert.equal(prospectingTestHelpers.decodeCfEmail("421"),"");});
test("Cloudflare data-cfemail rejects an empty value",()=>{assert.equal(prospectingTestHelpers.decodeCfEmail(""),"");});
test("malformed Cloudflare markup cannot crash public-email discovery",()=>{assert.doesNotThrow(()=>prospectingTestHelpers.extractPublicEmails("<a class=\"__cf_email__\" data-cfemail=\"not-hex\"><span"));assert.deepEqual(prospectingTestHelpers.extractPublicEmails("<span data-cfemail=\"4220273136\">ignored</span>"),[]);});
test("Cloudflare discovery preserves approval and send gates",async()=>withPublicPages({"/":"<a href=\"/contact.html\">Contact</a>","/contact.html":`<a href=\"/cdn-cgi/l/email-protection\" class=\"__cf_email__\" data-cfemail=\"${bestInShowCfEmail}\">[email&#160;protected]</a>`},async()=>{const discovered=await prospectingTestHelpers.inspectBusinessWebsite("http://www.bestinshowmaidstone.co.uk/","dog groomer");const db=recordingDb();const result=await runProspecting({GIFT_CARD_DB:db,AI_PROSPECTING_MIN_SCORE:"55",AI_EMAIL_SENDING_ENABLED:"false"},{trigger:"manual",now:"2026-08-30T00:00:00.000Z",candidates:[{business_name:"Best In Show Maidstone",business_type:"dog groomer",location:"Maidstone",source:"google_places",source_url:"https://www.google.com/maps/place/best-in-show",evidence:"Verified public business website",subscriber_type:"unknown",...discovered}],products:[matchProduct()]});assert.equal(result.prospectsQueued,0);assert.equal(db.calls.some(call=>call.type==="run"&&/outreach_messages/.test(call.sql)),false);assert.equal(db.calls.some(call=>call.type==="run"&&/status='(?:approved|sent)'/.test(call.sql)),false);}));
test("first-party discovery rejects external contact links and cross-domain redirects",async()=>withPublicPages({"/":"<a href=\"https://external.test/contact\">Contact</a><a href=\"/contact\">Contact</a>","/contact":{status:302,headers:{location:"https://external.test/contact"}}},async(calls)=>{const result=await prospectingTestHelpers.inspectBusinessWebsite("https://example.test/","dog groomer");assert.equal(result.email,"");assert.equal(calls.some(url=>url.includes("external.test")),false);}));
test("first-party discovery rejects private targets, deduplicates paths, observes the page limit, and leaves missing email empty",async()=>{let requests=0;const oldFetch=globalThis.fetch;globalThis.fetch=async(url)=>{requests+=1;return new Response(new URL(String(url)).pathname==="/"?Array.from({length:20},(_,index)=>`<a href=\"/contact-${index}\">Contact</a>`).join(""):"",{headers:{"Content-Type":"text/html"}});};try{const privateResult=await prospectingTestHelpers.inspectBusinessWebsite("http://127.0.0.1/contact","dog groomer");assert.equal(privateResult.website_verified,false);assert.equal(requests,0);const result=await prospectingTestHelpers.inspectBusinessWebsite("https://example.test/","dog groomer");assert.equal(result.email,"");assert.ok(requests<=8);}finally{globalThis.fetch=oldFetch;}});
test("public email provenance reuses existing prospect fields and source records without changing compliance",async()=>{const db=recordingDb();const prospect=prospectingTestHelpers.normaliseProspect({business_name:"Best In Show Maidstone",business_type:"dog groomer",website:"http://www.bestinshowmaidstone.co.uk/",website_verified:true,email:"bestinshowmaidstone@gmail.com",email_source_url:"http://www.bestinshowmaidstone.co.uk/contact.html",contact_page_url:"http://www.bestinshowmaidstone.co.uk/contact.html",email_source_type:"first_party_website",source:"google_places",source_url:"https://www.google.com/maps/place/example",evidence:"Verified public website"},"2026-08-20T00:00:00.000Z");await prospectingTestHelpers.upsertProspect(db,prospect,"2026-08-20T00:00:00.000Z");assert.ok(db.calls.some(call=>call.sql.includes("contact_page_url")));assert.ok(db.calls.some(call=>call.values.includes("business_website")&&call.values.includes("http://www.bestinshowmaidstone.co.uk/contact.html")));assert.equal(prospectingTestHelpers.complianceFor({...prospect,subscriber_type:"unknown"}),"pecr_consent_required");});
test("Jucridor's public mailbox does not bypass PECR consent and LIA gates",()=>{const prospect={email:"jucridor@gmail.com",subscriber_type:"unknown",lia_basis_recorded:false,lia_status:"not_recorded",consent_recorded:false,soft_opt_in_recorded:false};assert.equal(prospectingTestHelpers.pecrDecision(prospect),"unknown_treated_as_individual");assert.equal(prospectingTestHelpers.complianceFor(prospect),"pecr_consent_required");});

test("unknown subscriber cannot record an LIA",async()=>{const db=recordingDb({prospect:{email:"jucridor@gmail.com",domain:"jucridor.co.uk",subscriber_type:"unknown",subscriber_type_evidence:"",consent_recorded:0,soft_opt_in_recorded:0}});const body={confirmed:true,result:"passed",purpose:"Relevant products",necessity:"Proportionate contact",balancing:"Expectations, impact, nuisance, rights and safeguards reviewed",evidenceSource:"Public records",subscriberEvidence:"Not established",reviewerReference:"review-123",optOutConfirmed:true,suppressionConfirmed:true};const response=await handleProspectingRequest(req("/prospects/prospect-1/record-lia",{method:"POST",body:JSON.stringify(body)}),{ADMIN_API_TOKEN:"admin-token",GIFT_CARD_DB:db});assert.equal(response.status,409);assert.equal(db.calls.some(call=>call.type==="run"&&call.sql.includes("lia_status='passed'")),false);});
test("corporate LIA requires the complete three-part assessment and safeguards",async()=>{const prospect={email:"info@limited.test",domain:"limited.test",subscriber_type:"corporate",subscriber_type_evidence:"Companies House record",consent_recorded:0,soft_opt_in_recorded:0};const incomplete=await handleProspectingRequest(req("/prospects/p1/record-lia",{method:"POST",body:JSON.stringify({confirmed:true,result:"passed"})}),{ADMIN_API_TOKEN:"admin-token",GIFT_CARD_DB:recordingDb({prospect})});assert.equal(incomplete.status,400);const db=recordingDb({prospect});const body={confirmed:true,result:"passed",purpose:"Relevant trade outreach",necessity:"One proportionate contact",balancing:"Expectations, source, impact, nuisance, frequency, harm, rights and safeguards reviewed",evidenceSource:"Companies House record",subscriberEvidence:"Active limited company record",reviewerReference:"review-123",optOutConfirmed:true,suppressionConfirmed:true};const response=await handleProspectingRequest(req("/prospects/p1/record-lia",{method:"POST",body:JSON.stringify(body)}),{ADMIN_API_TOKEN:"admin-token",GIFT_CARD_DB:db});assert.equal(response.status,200);assert.ok(db.calls.some(call=>call.type==="run"&&call.values.includes("passed")));});
test("a failed corporate LIA remains blocked",async()=>{const prospect={email:"info@limited.test",domain:"limited.test",subscriber_type:"corporate",subscriber_type_evidence:"Companies House record",consent_recorded:0,soft_opt_in_recorded:0};const db=recordingDb({prospect});const body={confirmed:true,result:"failed",purpose:"Relevant trade outreach",necessity:"Contact was considered",balancing:"Impact and reasonable expectations outweigh the proposed interest",evidenceSource:"Companies House record",subscriberEvidence:"Active limited company record",reviewerReference:"review-124",optOutConfirmed:false,suppressionConfirmed:false};const response=await handleProspectingRequest(req("/prospects/p1/record-lia",{method:"POST",body:JSON.stringify(body)}),{ADMIN_API_TOKEN:"admin-token",GIFT_CARD_DB:db});assert.equal(response.status,200);const update=db.calls.find(call=>call.type==="run"&&call.sql.includes("lia_basis_recorded=?"));assert.ok(update.values.includes("failed"));assert.ok(update.values.includes(0));});

test("normalisation populates subscriber type, compliance evidence and retention",()=>{const p=prospectingTestHelpers.normaliseProspect({business_name:"Dog Grooming Ltd",business_type:"dog groomer",email:"info@dogs.test",subscriber_type:"corporate",subscriber_type_evidence:"Companies House record",lia_basis_recorded:true,lia_status:"passed",source:"companies_house",source_url:"https://find-and-update.company-information.service.gov.uk/company/1",evidence:"Active limited company"},"2026-08-11T00:00:00.000Z");assert.equal(p.subscriber_type,"corporate");assert.equal(p.subscriber_type_evidence,"Companies House record");assert.equal(p.lia_status,"passed");assert.equal(p.source_date,"2026-08-11");assert.equal(p.retention_expires_at,"2027-08-11T00:00:00.000Z");});

const matchProduct=(overrides={})=>({id:"product-1",name:"Professional Dog Grooming Towel",category:"Dog grooming",description:"Absorbent drying towel for coat care",source:"avasam",url:"https://bingodogwash.com/product.html?id=product-1",availability:"in stock",...overrides});
const matchProspect=(type,evidence=type)=>({business_name:`Example ${type}`,business_type:type,domain:"example.test",location:"London",source:"business_website",evidence});
const match=(prospect,products,minimum=55,env={})=>prospectingTestHelpers.bestMatch(prospect,prospectingTestHelpers.normaliseProducts(products,env),minimum);

test("deterministic matching selects a strong grooming product for a dog groomer",()=>{const result=match(matchProspect("dog groomer","Public website describes dog grooming and coat care"),[matchProduct()]);assert.equal(result.product.name,"Professional Dog Grooming Towel");assert.ok(result.score>=55);assert.match(result.reason,/grooming relevance/);});
test("deterministic matching selects walking or outdoor products for a dog walker",()=>{const result=match(matchProspect("dog walker","Verified dog walking service"),[matchProduct({name:"Reflective Dog Walking Harness",category:"Walking and outdoor",description:"Reflective harness and lead for outdoor walks"})]);assert.ok(result.score>=55);assert.match(result.reason,/walking and outdoor care/);});
test("deterministic matching selects suitable retail products for a pet shop",()=>{const result=match(matchProspect("pet shop","Public pet retail website"),[matchProduct({name:"Dog Enrichment Toy",category:"Pet toys",description:"Retail dog toy for enrichment"})]);assert.ok(result.score>=55);assert.match(result.reason,/pet retail/);});
test("deterministic matching selects operational care products for kennels and daycare",()=>{const result=match(matchProspect("dog daycare","Verified daycare and boarding service"),[matchProduct({name:"Washable Kennel Bedding",category:"Dog bedding",description:"Washable bedding for kennel care"})]);assert.ok(result.score>=55);assert.match(result.reason,/kennel and daycare operations/);});
test("unrelated businesses receive no supported product match",()=>{assert.equal(match(matchProspect("accountancy firm","Public accountancy listing"),[matchProduct()]),null);});
test("a candidate below the configured minimum remains unmatched",()=>{assert.equal(match(matchProspect("dog groomer"),[matchProduct({name:"Basic Groom Brush",category:"General",description:"Brush"})],96),null);});
test("unavailable products and products without a public URL are rejected",()=>{const prospect=matchProspect("dog groomer");assert.equal(match(prospect,[matchProduct({availability:"out of stock"})]),null);assert.equal(match(prospect,[matchProduct({url:""})]),null);});
test("disabled product sources are rejected",()=>{const prospect=matchProspect("pet shop");const etsy=matchProduct({source:"etsy",name:"Dog Enrichment Toy",category:"Pet toys",description:"Dog toy for enrichment"});assert.equal(match(prospect,[etsy],55,{ETSY_FEATURE_ENABLED:"false",ETSY_SYNC_ENABLED:"false"}),null);});
test("every supported category has a deterministic, bounded targeting profile",()=>{for(const [category,label,offer] of [["dog groomer","grooming","BINGO_SHOP"],["pet shop","pet retail","BINGO_SHOP"],["dog walker","walking and outdoor care","DOG_WALKER_DIRECTORY"],["kennel","kennel and boarding care","BINGO_SHOP"],["dog daycare","kennel and daycare operations","BINGO_SHOP"],["pet hotel","boarding and guest care","BINGO_SHOP"],["veterinary clinic","non-medical pet care","BINGO_SHOP"],["animal charity","animal care and community","BINGO_SHOP"]]){const profile=prospectingTestHelpers.categoryTargetingProfile(category);assert.equal(profile.label,label);assert.equal(profile.offer,offer);assert.ok(profile.signalTerms.length);assert.ok(profile.productTerms.length);}});
test("research signals influence transparent matching and keep category offers separate",()=>{const prospect={...matchProspect("dog walker","Verified public business website"),public_interest_signals:[{signal:"Public website mentions group walks",source_url:"https://example.test/services"}]};const result=match(prospect,[matchProduct({name:"Reflective Dog Walking Harness",category:"Walking and outdoor",description:"Reflective harness and lead for group walks"})]);assert.match(result.reason,/group walks/);assert.equal(result.matched_bingo_offer.id,"DOG_WALKER_DIRECTORY");assert.ok(result.score_breakdown.service_match>0);assert.equal(match(matchProspect("dog groomer","Verified grooming service"),[matchProduct()]).matched_bingo_offer.id,"BINGO_SHOP");});
test("veterinary and charity profiles avoid medical claims and invented donation promises",async()=>{const vet=prospectingTestHelpers.categoryTargetingProfile("veterinary clinic");const charity=prospectingTestHelpers.categoryTargetingProfile("animal charity");assert.match(vet.avoid.join(" "),/medical claims/);assert.match(charity.avoid.join(" "),/donation promises/);const product=prospectingTestHelpers.normaliseProducts([matchProduct({name:"Dog Care Towel",category:"Hygiene",description:"General non-medical dog care towel"})]);const prospect={...matchProspect("veterinary clinic","Public website mentions puppy clinic"),public_interest_signals:[{signal:"Public website mentions puppy clinic",source_url:"https://example.test/about"}]};const matchResult=prospectingTestHelpers.bestMatch(prospect,product,55);const draft=await prospectingTestHelpers.generateDraft({},prospect,matchResult);assert.doesNotMatch(draft.body,/treat|veterinary endorsement|donation/i);assert.match(draft.body,/non-medical/i);});
test("grounded per-prospect drafts use only public evidence and a verified contact name",async()=>{const prospect={...matchProspect("dog walker","Verified public business website"),business_name:"Maidstone Walks",website:"https://example.test/",contact_name:"Rebecca Smith",contact_name_source_url:"https://www.example.test/contact",public_interest_signals:[{signal:"Public website mentions group walks",source_url:"https://example.test/services"}]};const matchResult=match(prospect,[matchProduct({name:"Reflective Dog Walking Harness",category:"Walking and outdoor",description:"Reflective harness and lead for group walks"})]);const draft=await prospectingTestHelpers.generateDraft({},prospect,matchResult);assert.match(draft.body,/^Hi Rebecca,/);assert.match(draft.body,/group walks/);assert.match(draft.body,/Dog Walker Directory/);assert.doesNotMatch(draft.body,/searching for|browsing history|wholesale|guaranteed/i);const anonymous=await prospectingTestHelpers.generateDraft({}, {...prospect,contact_name_source_url:""},matchResult);assert.match(anonymous.body,/^Hello Maidstone Walks team,/);});
test("low relevance produces no match, while the physical wash offer remains explicitly in development",()=>{assert.equal(match(matchProspect("dog walker","Verified public dog walking business"),[matchProduct({name:"Dog Enrichment Toy",category:"Pet toys",description:"Retail enrichment toy"})]),null);assert.match(prospectingTestHelpers.BINGO_OFFERS.DOG_WASH.description,/still in development and is not currently open/);});
test("Customer Finder keeps its table while surfacing first-party email and research provenance",()=>{const source=readFileSync(new URL("../public/admin/ai-drafts.js",import.meta.url),"utf8");const row=source.slice(source.indexOf("function prospectSourceDetails"),source.indexOf("async function prospectingAction"));assert.match(row,/email_source_url\|\|p\.contact_page_url/);assert.match(row,/First-party website verified/);assert.match(row,/research_summary/);assert.match(row,/research_source_urls/);});
test("AI cannot override deterministic product eligibility",async()=>{const db=recordingDb();const result=await runProspecting({GIFT_CARD_DB:db,AI_PROSPECTING_MIN_SCORE:"55",AI:{run:async()=>({response:JSON.stringify({subject:"Invented match",body:"Invented body"})})}},{trigger:"manual",now:"2026-08-14T00:00:00.000Z",candidates:[{...matchProspect("dog groomer"),email:"info@example.test",subscriber_type:"corporate",lia_basis_recorded:true,lia_status:"passed",source_url:"https://example.test"}],products:[matchProduct({availability:"unavailable"})]});assert.equal(result.prospectsQueued,0);assert.equal(db.calls.some(call=>call.sql.includes("outreach_messages")&&call.type==="run"),false);});
test("compliance-blocked prospects may retain an explainable match but never receive a draft",async()=>{const db=recordingDb();const result=await runProspecting({GIFT_CARD_DB:db,AI_PROSPECTING_MIN_SCORE:"55",AI:{run:async()=>{throw new Error("AI must not run");}}},{trigger:"manual",now:"2026-08-15T00:00:00.000Z",candidates:[{...matchProspect("dog groomer"),email:"",subscriber_type:"unknown",lia_basis_recorded:false,source_url:"https://example.test"}],products:[matchProduct()]});assert.equal(result.prospectsQueued,0);assert.ok(db.calls.some(call=>call.sql.includes("prospect_product_matches")&&call.type==="run"));assert.ok(db.calls.some(call=>call.sql.includes("UPDATE prospects SET compliance_status")&&call.values.includes("missing_public_email")));assert.equal(db.calls.some(call=>call.sql.includes("outreach_messages")&&call.type==="run"),false);});
test("corporate plus passed LIA creates only an unapproved human-review draft and never sends",async()=>{const db=recordingDb({suppressionSequence:[false,false]});let providerCalls=0;const oldFetch=globalThis.fetch;globalThis.fetch=async()=>{providerCalls+=1;return Response.json({});};try{const result=await runProspecting({GIFT_CARD_DB:db,AI_PROSPECTING_MIN_SCORE:"55",AI_EMAIL_SENDING_ENABLED:"false",AI:{run:async()=>({response:JSON.stringify({subject:"Relevant product",body:"Bingo Dog Wash offers an evidence-based product. Reply unsubscribe to opt out."})})}},{trigger:"manual",now:"2026-08-16T00:00:00.000Z",candidates:[{...matchProspect("dog groomer"),email:"info@example.test",subscriber_type:"corporate",lia_basis_recorded:true,lia_status:"passed",source_url:"https://example.test"}],products:[matchProduct()]});assert.equal(result.prospectsQueued,1);const insert=db.calls.find(call=>call.sql.includes("INSERT INTO outreach_messages"));assert.ok(insert);assert.ok(insert.values.includes("draft"));assert.equal(insert.values.includes("approved"),false);assert.equal(providerCalls,0);}finally{globalThis.fetch=oldFetch;}});

test("cost cap aborts cleanly before AI drafting",async()=>{const db=recordingDb();const result=await runProspecting({GIFT_CARD_DB:db,AI_PROSPECTING_MAX_COST_GBP:"0",AI_PROSPECTING_AI_ESTIMATED_COST_GBP:"0.01",AI_PROSPECTING_MIN_SCORE:"35"},{trigger:"manual",now:"2026-08-11T00:00:00.000Z",candidates:[{business_name:"Dog Grooming Ltd",business_type:"dog groomer",email:"info@dogs.test",subscriber_type:"corporate",lia_basis_recorded:true,lia_status:"passed",source:"companies_house",source_url:"https://find-and-update.company-information.service.gov.uk/company/1",evidence:"dog grooming business"}],products:[{id:"p1",name:"Dog Grooming Towel",category:"dog grooming",description:"grooming towel",url:"https://bingodogwash.com/shop"}]});assert.equal(result.partial,true);assert.equal(result.prospectsQueued,0);assert.equal(result.searchApiCost,0);});

test("completed nightly retry is idempotent",async()=>{const existing={id:"run-1",status:"completed",prospects_queued:2};const db=recordingDb({existingRun:existing});const result=await runProspecting({GIFT_CARD_DB:db},{trigger:"scheduled",now:"2026-08-11T02:00:00.000Z"});assert.equal(result.idempotent,true);assert.equal(result.run,existing);assert.equal(db.calls.some(c=>c.type==="run"),false);});

test("retention job purges dependent data and only expired untouched prospects",async()=>{const db=recordingDb({changes:3});const result=await purgeExpiredProspects(db,"2026-08-11T03:30:00.000Z");assert.equal(result.purged,3);assert.equal(db.calls.filter(c=>c.type==="run").length,4);assert.ok(db.calls.every(c=>/converted_at IS NULL AND last_contacted_at IS NULL/.test(c.sql)));});

test("disabled schedule performs no source or email work",async()=>{const db=recordingDb();const oldFetch=globalThis.fetch;let requests=0;globalThis.fetch=async()=>{requests+=1;return Response.json({});};try{const result=await runProspectingSchedule({cron:prospectingTestHelpers.NIGHTLY_CRON,scheduledTime:Date.now()},{GIFT_CARD_DB:db,AI_PROSPECTING_ENABLED:"false",AI_EMAIL_SENDING_ENABLED:"false"});assert.equal(result.skipped,true);assert.equal(requests,0);assert.equal(db.calls.length,0);}finally{globalThis.fetch=oldFetch;}});

test("scheduled catalogue loading retains Worker env context for provider reads",async()=>{const db=recordingDb();const pending=[];const oldFetch=globalThis.fetch;let credentialBody="";let emailRequests=0;globalThis.fetch=async(url,options={})=>{const target=String(url);if(target.includes("auth")||target.includes("token")){credentialBody=String(options.body||"");return Response.json({access_token:"scheduled-test-token"});}if(target.includes("product")){return Response.json([{id:"scheduled-product",name:"Dog Grooming Towel",description:"Absorbent grooming towel",price:10,stock:2}]);}if(target.includes("brevo")||target.includes("resend")){emailRequests+=1;}return Response.json({products:[]});};try{await worker.scheduled({cron:prospectingTestHelpers.NIGHTLY_CRON,scheduledTime:Date.parse("2026-08-17T02:00:00.000Z")},{GIFT_CARD_DB:db,AI_PROSPECTING_ENABLED:"true",AI_EMAIL_SENDING_ENABLED:"false",AVASAM_CONSUMER_KEY:"scheduled-consumer",AVASAM_SECRET_KEY:"scheduled-secret",ETSY_FEATURE_ENABLED:"false",ETSY_SYNC_ENABLED:"false"},{waitUntil(promise){pending.push(Promise.resolve(promise));}});await Promise.all(pending);assert.match(credentialBody,/scheduled-consumer/);assert.match(credentialBody,/scheduled-secret/);assert.equal(emailRequests,0);}finally{globalThis.fetch=oldFetch;}});

test("sending remains blocked without the send flag even after approval",async()=>{const db=recordingDb({message:{id:"m1",provider:"brevo",status:"approved",compliance_status:"eligible",email:"info@dogs.test",domain:"dogs.test",subscriber_type:"corporate",lia_basis_recorded:1,lia_status:"passed",consent_recorded:0,soft_opt_in_recorded:0}});const response=await handleProspectingRequest(req("/messages/m1/send",{method:"POST",body:"{}"}),{ADMIN_API_TOKEN:"admin-token",GIFT_CARD_DB:db,AI_EMAIL_SENDING_ENABLED:"false"});assert.equal(response.status,409);assert.equal((await response.json()).error,"Email sending is disabled.");});

test("suppression is checked before drafting and again before queueing",async()=>{const candidate={business_name:"Dog Grooming Ltd",business_type:"dog groomer",email:"info@dogs.test",subscriber_type:"corporate",lia_basis_recorded:true,source:"companies_house",source_url:"https://find-and-update.company-information.service.gov.uk/company/1",evidence:"dog grooming business"};const product={id:"p1",name:"Dog Grooming Towel",category:"dog grooming",description:"grooming towel",url:"https://bingodogwash.com/shop"};const draftBlocked=await runProspecting({GIFT_CARD_DB:recordingDb({suppressed:true}),AI_PROSPECTING_MIN_SCORE:"35"},{trigger:"manual",now:"2026-08-12T00:00:00.000Z",candidates:[candidate],products:[product]});assert.equal(draftBlocked.blocked,1);const queueDb=recordingDb({suppressionSequence:[false,true]});const queueBlocked=await runProspecting({GIFT_CARD_DB:queueDb,AI_PROSPECTING_MIN_SCORE:"35",AI:{run:async()=>({response:JSON.stringify({subject:"Relevant towel",body:"Source-backed outreach"})})}},{trigger:"manual",now:"2026-08-13T00:00:00.000Z",candidates:[candidate],products:[product]});assert.equal(queueBlocked.blocked,1);assert.equal(queueBlocked.prospectsQueued,0);});

test("cooldown remains fail closed for a recently contacted prospect",()=>{assert.equal(prospectingTestHelpers.cooldownActive({last_contacted_at:"2026-08-20T00:00:00.000Z"},"2026-08-23T00:00:00.000Z",30),true);assert.equal(prospectingTestHelpers.cooldownActive({last_contacted_at:"2026-07-01T00:00:00.000Z"},"2026-08-23T00:00:00.000Z",30),false);});
test("duplicate outreach insertion is blocked instead of counted as a queued draft",async()=>{const db=recordingDb({changes:0});const result=await runProspecting({GIFT_CARD_DB:db,AI_PROSPECTING_MIN_SCORE:"35",AI:{run:async()=>({response:JSON.stringify({subject:"Relevant towel",body:"Bingo Dog Wash. Reply unsubscribe to opt out."})})}},{trigger:"manual",now:"2026-08-23T00:00:00.000Z",candidates:[{business_name:"Dog Grooming Ltd",business_type:"dog groomer",email:"info@dogs.test",subscriber_type:"corporate",lia_basis_recorded:true,lia_status:"passed",source:"companies_house",source_url:"https://find-and-update.company-information.service.gov.uk/company/1",evidence:"dog grooming business"}],products:[{id:"p1",name:"Dog Grooming Towel",category:"dog grooming",description:"grooming towel",url:"https://bingodogwash.com/shop"}]});assert.equal(result.prospectsQueued,0);assert.ok(db.calls.some(call=>call.type==="run"&&call.sql.includes("compliance_status='duplicate_outreach'")));});
test("suppression or a previous objection blocks approval regardless of a passed LIA",async()=>{const db=recordingDb({suppressed:true,message:{id:"m1",provider:"brevo",status:"draft",compliance_status:"eligible",email:"info@dogs.test",domain:"dogs.test",subscriber_type:"corporate",lia_basis_recorded:1,lia_status:"passed",consent_recorded:0,soft_opt_in_recorded:0}});const response=await handleProspectingRequest(req("/messages/m1/approve",{method:"POST",body:"{}"}),{ADMIN_API_TOKEN:"admin-token",GIFT_CARD_DB:db});assert.equal(response.status,409);assert.equal(db.calls.some(call=>call.type==="run"&&call.sql.includes("status='approved'")),false);});
test("delivery requires independent human approval even when every compliance gate passes",async()=>{const oldFetch=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls+=1;return Response.json({});};const db=recordingDb({message:{id:"m1",provider:"brevo",status:"draft",compliance_status:"eligible",email:"info@dogs.test",domain:"dogs.test",subscriber_type:"corporate",lia_basis_recorded:1,lia_status:"passed",consent_recorded:0,soft_opt_in_recorded:0}});try{const response=await handleProspectingRequest(req("/messages/m1/send",{method:"POST",body:"{}"}),{ADMIN_API_TOKEN:"admin-token",GIFT_CARD_DB:db,AI_EMAIL_SENDING_ENABLED:"true",AI_EMAIL_CAMPAIGN_PROVIDER:"brevo",BREVO_API_KEY:"private",BREVO_OUTREACH_TEMPLATE_ID:"1",BREVO_OUTREACH_LIST_ID:"2",AI_EMAIL_SENDER_EMAIL:"hello@bingodogwash.com",AI_EMAIL_SENDER_NAME:"Bingo Dog Wash"});assert.equal(response.status,409);assert.equal(calls,0);}finally{globalThis.fetch=oldFetch;}});

test("Brevo provider failure is isolated and records no social-channel writes",async()=>{const db=recordingDb({message:{id:"m1",provider:"brevo",status:"approved",compliance_status:"eligible",email:"info@dogs.test",domain:"dogs.test",subscriber_type:"corporate",lia_basis_recorded:1,lia_status:"passed",consent_recorded:0,soft_opt_in_recorded:0}});const oldFetch=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls+=1;return calls===1?Response.json({}, {status:201}):Response.json({message:"rejected"},{status:500});};try{const response=await handleProspectingRequest(req("/messages/m1/send",{method:"POST",body:"{}"}),{ADMIN_API_TOKEN:"admin-token",GIFT_CARD_DB:db,AI_EMAIL_SENDING_ENABLED:"true",AI_EMAIL_CAMPAIGN_PROVIDER:"brevo",BREVO_API_KEY:"private",BREVO_OUTREACH_TEMPLATE_ID:"12",BREVO_OUTREACH_LIST_ID:"34",AI_EMAIL_SENDER_EMAIL:"campaigns@bingodogwash.com",AI_EMAIL_SENDER_NAME:"Bingo Dog Wash"});assert.equal(response.status,502);const body=await response.json();assert.equal(body.provider,"brevo");assert.match(body.error,/other distribution channels are unaffected/);assert.equal(db.calls.some(call=>/marketing_posts|marketing_platform_results|tiktok/i.test(call.sql)),false);}finally{globalThis.fetch=oldFetch;}});

test("authenticated Brevo suppression webhook is authoritative",async()=>{const db=recordingDb();const unauthorised=await handleBrevoWebhook(new Request("https://bingodogwash.com/api/webhooks/brevo/outreach",{method:"POST",body:"{}"}),{GIFT_CARD_DB:db,BREVO_WEBHOOK_SECRET:"secret"});assert.equal(unauthorised.status,401);const response=await handleBrevoWebhook(new Request("https://bingodogwash.com/api/webhooks/brevo/outreach",{method:"POST",headers:{Authorization:"Bearer secret","Content-Type":"application/json"},body:JSON.stringify({event:"hardBounce",email:"Info@Dogs.test","message-id":"brevo-message"})}),{GIFT_CARD_DB:db,BREVO_WEBHOOK_SECRET:"secret"});assert.equal(response.status,200);assert.equal((await response.json()).suppressed,1);assert.ok(db.calls.some(call=>call.sql.includes("outreach_message_events")&&call.values.includes("hardbounce")));assert.ok(db.calls.some(call=>call.sql.includes("suppression_list")&&call.values.includes("brevo:hardbounce")));assert.ok(db.calls.some(call=>call.sql.includes("status IN ('draft','approved','queued')")));assert.ok(db.calls.some(call=>call.sql.includes("provider='brevo'")&&call.values.includes("brevo-message")));});

test("Brevo webhook isolates malformed payloads and individual batch failures",async()=>{const malformed=await handleBrevoWebhook(new Request("https://bingodogwash.com/api/webhooks/brevo/outreach",{method:"POST",headers:{Authorization:"Bearer secret","Content-Type":"application/json"},body:"{"}),{GIFT_CARD_DB:recordingDb(),BREVO_WEBHOOK_SECRET:"secret"});assert.equal(malformed.status,200);assert.equal((await malformed.json()).invalidPayload,true);const successfulEmails=[];const db={prepare(sql){let values=[];return {bind(...next){values=next;return this;},async run(){if(sql.includes("outreach_message_events")&&values.includes("bad@dogs.test"))throw new Error("row failure");if(sql.includes("suppression_list"))successfulEmails.push(values[1]);return {success:true};}};}};const response=await handleBrevoWebhook(new Request("https://bingodogwash.com/api/webhooks/brevo/outreach",{method:"POST",headers:{Authorization:"Bearer secret","Content-Type":"application/json"},body:JSON.stringify([{event:"spam",email:"bad@dogs.test"},{event:"unsubscribed",email:"good@dogs.test"}])}),{GIFT_CARD_DB:db,BREVO_WEBHOOK_SECRET:"secret"});const result=await response.json();assert.equal(response.status,200);assert.equal(result.failed,1);assert.equal(result.suppressed,1);assert.deepEqual(successfulEmails,["good@dogs.test"]);});

test("schema and scheduler preserve explicit compliance and never schedule sending",()=>{const migration=readFileSync(new URL("../migrations/0016_ai_customer_finder.sql",import.meta.url),"utf8");const worker=readFileSync(new URL("../_functions_NOT_FOR_STATIC_UPLOAD/api/worker.js",import.meta.url),"utf8");assert.match(migration,/subscriber_type TEXT NOT NULL DEFAULT 'unknown'/);assert.match(migration,/lia_basis_recorded INTEGER NOT NULL DEFAULT 0/);assert.match(migration,/search_api_cost REAL NOT NULL/);assert.match(migration,/provider TEXT NOT NULL DEFAULT 'brevo'/);const scheduled=worker.slice(worker.indexOf("async scheduled("),worker.indexOf("async function handleRequestWithAssets"));assert.match(scheduled,/runProspectingSchedule/);assert.doesNotMatch(scheduled,/EMAIL\.send|api\.brevo|api\.resend/);});
test("additive compliance migration preserves legacy LIA history without treating it as a new passed assessment",()=>{const migration=readFileSync(new URL("../migrations/0026_customer_finder_compliance_workflow.sql",import.meta.url),"utf8");for(const field of ["subscriber_type_evidence","consent_evidence","soft_opt_in_recorded","soft_opt_in_evidence","lia_status","lia_purpose_test","lia_necessity_test","lia_balancing_test","lia_reviewer_reference","lia_opt_out_confirmed","lia_suppression_confirmed"])assert.match(migration,new RegExp(`ADD COLUMN ${field}`));assert.match(migration,/lia_status='legacy_recorded' WHERE lia_basis_recorded=1/);assert.doesNotMatch(migration,/DROP TABLE|DELETE FROM/);});
