import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { handleBrevoWebhook, handleProspectingRequest, purgeExpiredProspects, runProspecting, runProspectingSchedule, prospectingTestHelpers } from "../_functions_NOT_FOR_STATIC_UPLOAD/api/prospecting.js";
import worker from "../_functions_NOT_FOR_STATIC_UPLOAD/api/worker.js";

const auth={Authorization:"Bearer admin-token","Content-Type":"application/json"};
const req=(path="",options={})=>new Request(`https://admin.bingodogwash.com/api/admin/prospecting${path}`,{headers:{...auth,...options.headers},...options});

function recordingDb(options={}){const calls=[];return {calls,prepare(sql){let values=[];return {bind(...next){values=next;return this;},async first(){calls.push({sql,values,type:"first"});if(sql.includes("outreach_runs WHERE idempotency_key"))return options.existingRun||null;if(sql.includes("outreach_messages o JOIN prospects"))return options.message||null;if(sql.includes("suppression_list")){const blocked=options.suppressionSequence?.length?options.suppressionSequence.shift():options.suppressed;return blocked?{blocked:1}:null;}return null;},async all(){calls.push({sql,values,type:"all"});return {results:[]};},async run(){calls.push({sql,values,type:"run"});return {success:true,meta:{changes:options.changes??1}};}};}};}

test("prospecting endpoints require admin authorisation",async()=>{const response=await handleProspectingRequest(new Request("https://admin.bingodogwash.com/api/admin/prospecting"),{ADMIN_API_TOKEN:"admin-token"});assert.equal(response.status,401);});

test("manual prospecting is independently blocked while its feature flag is false",async()=>{const response=await handleProspectingRequest(req("/run",{method:"POST",body:"{}"}),{ADMIN_API_TOKEN:"admin-token",GIFT_CARD_DB:recordingDb(),AI_PROSPECTING_ENABLED:"false",AI_MANUAL_PROSPECTING_ENABLED:"false"});assert.equal(response.status,409);});

async function manualCatalogueRequest(body,loadProducts){const db=recordingDb();const oldFetch=globalThis.fetch;globalThis.fetch=async()=>Response.json({places:[{id:"manual-place",displayName:{text:"Example Dog Groomer"},formattedAddress:"London",primaryType:"pet_groomer",types:["pet_groomer"],businessStatus:"OPERATIONAL",googleMapsUri:"https://maps.google.com/example"}]});try{const input={location:"London",categories:["dog groomer"],budget:0.09,maxProspects:5,...body};const response=await handleProspectingRequest(req("/run",{method:"POST",body:JSON.stringify(input)}),{ADMIN_API_TOKEN:"admin-token",GIFT_CARD_DB:db,AI_PROSPECTING_ENABLED:"false",AI_MANUAL_PROSPECTING_ENABLED:"true",AI_EMAIL_SENDING_ENABLED:"false",GOOGLE_PLACES_API_KEY:"test-key",AI_PROSPECTING_SEARCH_TERMS:"dog groomer",AI_PROSPECTING_SEARCH_LOCATIONS:"London",AI_PROSPECTING_MIN_SCORE:"55",AI_PROSPECTING_MAX_COST_GBP:"0.25"},undefined,{loadProducts});return {response,db};}finally{globalThis.fetch=oldFetch;}}
test("manual request uses a non-empty submitted product catalogue",async()=>{let loads=0;const {response,db}=await manualCatalogueRequest({products:[matchProduct()]},async()=>{loads+=1;throw new Error("loader must not run");});assert.equal(response.status,200);assert.equal(loads,0);assert.ok(db.calls.some(call=>call.sql.includes("prospect_product_matches")&&call.type==="run"));});
test("manual request with an empty product array loads the canonical catalogue",async()=>{let loads=0;const {response,db}=await manualCatalogueRequest({products:[]},async()=>{loads+=1;return [matchProduct()];});assert.equal(response.status,200);assert.equal(loads,1);assert.ok(db.calls.some(call=>call.sql.includes("prospect_product_matches")&&call.type==="run"));});
test("manual request without products loads the canonical catalogue",async()=>{let loads=0;const {response,db}=await manualCatalogueRequest({},async()=>{loads+=1;return [matchProduct()];});assert.equal(response.status,200);assert.equal(loads,1);assert.ok(db.calls.some(call=>call.sql.includes("prospect_product_matches")&&call.type==="run"));});
test("manual request with invalid products loads the canonical catalogue",async()=>{let loads=0;const {response,db}=await manualCatalogueRequest({products:[null,"invalid"]},async()=>{loads+=1;return [matchProduct()];});assert.equal(response.status,200);assert.equal(loads,1);assert.ok(db.calls.some(call=>call.sql.includes("prospect_product_matches")&&call.type==="run"));});

test("manual discovery controls accept approved presets and conservative custom locations",()=>{const validate=prospectingTestHelpers.manualPreferences;const env={AI_PROSPECTING_MAX_COST_GBP:"0.25",AI_PROSPECTING_MAX_PROSPECTS:"20"};for(const location of ["Maidstone","Kent","London","South East England","United Kingdom","King's Lynn, Norfolk"]){const result=validate({location,categories:["dog groomer","pet shop"],budget:0.09,maxProspects:10},env);assert.equal(result.ok,true);assert.equal(result.value.location,location);assert.equal(result.value.manualGoogle,true);}});
test("manual discovery controls reject arbitrary categories, unsafe locations and server-cap bypasses",()=>{const validate=prospectingTestHelpers.manualPreferences;const env={AI_PROSPECTING_MAX_COST_GBP:"0.15",AI_PROSPECTING_MAX_PROSPECTS:"10"};assert.equal(validate({location:"London",categories:[],budget:0.03,maxProspects:5},env).ok,false);assert.equal(validate({location:"London",categories:["accountant"],budget:0.03,maxProspects:5},env).ok,false);assert.equal(validate({location:"London<script>",categories:["dog groomer"],budget:0.03,maxProspects:5},env).ok,false);assert.equal(validate({location:{city:"London"},categories:["dog groomer"],budget:0.03,maxProspects:5},env).ok,false);assert.equal(validate({location:"London",categories:["dog groomer"],budget:"0.03",maxProspects:5},env).ok,false);assert.equal(validate({location:"London",categories:["dog groomer"],budget:0.25,maxProspects:5},env).ok,false);assert.equal(validate({location:"London",categories:["dog groomer"],budget:0.03,maxProspects:100},env).ok,false);});
test("manual discovery remains available without enabling the nightly schedule",async()=>{const {response}=await manualCatalogueRequest({products:[matchProduct()]},async()=>[]);assert.equal(response.status,200);});

test("subscriber type and LIA gates fail closed",()=>{const gate=prospectingTestHelpers.complianceFor;assert.equal(gate({email:"info@limited.test",subscriber_type:"corporate",lia_basis_recorded:false}),"lia_required");assert.equal(gate({email:"owner@sole.test",subscriber_type:"individual",lia_basis_recorded:true,consent_recorded:false}),"pecr_consent_required");assert.equal(gate({email:"hello@unknown.test",subscriber_type:"unknown",lia_basis_recorded:true,consent_recorded:false}),"pecr_consent_required");assert.equal(gate({email:"info@limited.test",subscriber_type:"corporate",lia_basis_recorded:true}),"eligible");});

test("normalisation populates subscriber type, LIA and retention for every prospect",()=>{const p=prospectingTestHelpers.normaliseProspect({business_name:"Dog Grooming Ltd",business_type:"dog groomer",email:"info@dogs.test",subscriber_type:"corporate",lia_basis_recorded:true,source:"companies_house",source_url:"https://find-and-update.company-information.service.gov.uk/company/1",evidence:"Active limited company"},"2026-08-11T00:00:00.000Z");assert.equal(p.subscriber_type,"corporate");assert.equal(p.lia_basis_recorded,true);assert.equal(p.source_date,"2026-08-11");assert.equal(p.retention_expires_at,"2027-08-11T00:00:00.000Z");});

const matchProduct=(overrides={})=>({id:"product-1",name:"Professional Dog Grooming Towel",category:"Dog grooming",description:"Absorbent drying towel for coat care",source:"avasam",url:"https://bingodogwash.com/product.html?id=product-1",availability:"in stock",...overrides});
const matchProspect=(type,evidence=type)=>({business_name:`Example ${type}`,business_type:type,domain:"example.test",location:"London",source:"business_website",evidence});
const match=(prospect,products,minimum=55,env={})=>prospectingTestHelpers.bestMatch(prospect,prospectingTestHelpers.normaliseProducts(products,env),minimum);

test("deterministic matching selects a strong grooming product for a dog groomer",()=>{const result=match(matchProspect("dog groomer","Public website describes dog grooming and coat care"),[matchProduct()]);assert.equal(result.product.name,"Professional Dog Grooming Towel");assert.ok(result.score>=55);assert.match(result.reason,/grooming relevance/);});
test("deterministic matching selects walking or outdoor products for a dog walker",()=>{const result=match(matchProspect("dog walker","Verified dog walking service"),[matchProduct({name:"Reflective Dog Walking Harness",category:"Walking and outdoor",description:"Reflective harness and lead for outdoor walks"})]);assert.ok(result.score>=55);assert.match(result.reason,/walking and outdoor care/);});
test("deterministic matching selects suitable retail products for a pet shop",()=>{const result=match(matchProspect("pet shop","Public pet retail website"),[matchProduct({name:"Dog Enrichment Toy",category:"Pet toys",description:"Retail dog toy for enrichment"})]);assert.ok(result.score>=55);assert.match(result.reason,/pet retail/);});
test("deterministic matching selects operational care products for kennels and daycare",()=>{const result=match(matchProspect("dog daycare","Verified daycare and boarding service"),[matchProduct({name:"Washable Kennel Bedding",category:"Dog bedding",description:"Washable bedding for kennel care"})]);assert.ok(result.score>=55);assert.match(result.reason,/kennel and daycare operations/);});
test("unrelated businesses receive no supported product match",()=>{assert.equal(match(matchProspect("accountancy firm","Public accountancy listing"),[matchProduct()]),null);});
test("a candidate below the configured minimum remains unmatched",()=>{assert.equal(match(matchProspect("dog groomer"),[matchProduct({name:"Basic Groom Brush",category:"General",description:"Brush"})],96),null);});
test("unavailable products and products without a public URL are rejected",()=>{const prospect=matchProspect("dog groomer");assert.equal(match(prospect,[matchProduct({availability:"out of stock"})]),null);assert.equal(match(prospect,[matchProduct({url:""})]),null);});
test("disabled product sources are rejected",()=>{const prospect=matchProspect("pet shop");const etsy=matchProduct({source:"etsy",name:"Dog Enrichment Toy",category:"Pet toys",description:"Dog toy for enrichment"});assert.equal(match(prospect,[etsy],55,{ETSY_FEATURE_ENABLED:"false",ETSY_SYNC_ENABLED:"false"}),null);});
test("AI cannot override deterministic product eligibility",async()=>{const db=recordingDb();const result=await runProspecting({GIFT_CARD_DB:db,AI_PROSPECTING_MIN_SCORE:"55",AI:{run:async()=>({response:JSON.stringify({subject:"Invented match",body:"Invented body"})})}},{trigger:"manual",now:"2026-08-14T00:00:00.000Z",candidates:[{...matchProspect("dog groomer"),email:"info@example.test",subscriber_type:"corporate",lia_basis_recorded:true,source_url:"https://example.test"}],products:[matchProduct({availability:"unavailable"})]});assert.equal(result.prospectsQueued,0);assert.equal(db.calls.some(call=>call.sql.includes("outreach_messages")&&call.type==="run"),false);});
test("compliance-blocked prospects may retain an explainable match but never receive a draft",async()=>{const db=recordingDb();const result=await runProspecting({GIFT_CARD_DB:db,AI_PROSPECTING_MIN_SCORE:"55",AI:{run:async()=>{throw new Error("AI must not run");}}},{trigger:"manual",now:"2026-08-15T00:00:00.000Z",candidates:[{...matchProspect("dog groomer"),email:"",subscriber_type:"unknown",lia_basis_recorded:false,source_url:"https://example.test"}],products:[matchProduct()]});assert.equal(result.prospectsQueued,0);assert.ok(db.calls.some(call=>call.sql.includes("prospect_product_matches")&&call.type==="run"));assert.ok(db.calls.some(call=>call.sql.includes("UPDATE prospects SET compliance_status")&&call.values.includes("missing_public_email")));assert.equal(db.calls.some(call=>call.sql.includes("outreach_messages")&&call.type==="run"),false);});
test("generated outreach remains an unapproved human-review draft and never sends",async()=>{const db=recordingDb({suppressionSequence:[false,false]});let providerCalls=0;const oldFetch=globalThis.fetch;globalThis.fetch=async()=>{providerCalls+=1;return Response.json({});};try{const result=await runProspecting({GIFT_CARD_DB:db,AI_PROSPECTING_MIN_SCORE:"55",AI_EMAIL_SENDING_ENABLED:"false",AI:{run:async()=>({response:JSON.stringify({subject:"Relevant product",body:"Evidence-based draft. Reply unsubscribe to opt out."})})}},{trigger:"manual",now:"2026-08-16T00:00:00.000Z",candidates:[{...matchProspect("dog groomer"),email:"info@example.test",subscriber_type:"corporate",lia_basis_recorded:true,source_url:"https://example.test"}],products:[matchProduct()]});assert.equal(result.prospectsQueued,1);const insert=db.calls.find(call=>call.sql.includes("INSERT INTO outreach_messages"));assert.ok(insert);assert.ok(insert.values.includes("draft"));assert.equal(insert.values.includes("approved"),false);assert.equal(providerCalls,0);}finally{globalThis.fetch=oldFetch;}});

test("cost cap aborts cleanly before AI drafting",async()=>{const db=recordingDb();const result=await runProspecting({GIFT_CARD_DB:db,AI_PROSPECTING_MAX_COST_GBP:"0",AI_PROSPECTING_AI_ESTIMATED_COST_GBP:"0.01",AI_PROSPECTING_MIN_SCORE:"35"},{trigger:"manual",now:"2026-08-11T00:00:00.000Z",candidates:[{business_name:"Dog Grooming Ltd",business_type:"dog groomer",email:"info@dogs.test",subscriber_type:"corporate",lia_basis_recorded:true,source:"companies_house",source_url:"https://find-and-update.company-information.service.gov.uk/company/1",evidence:"dog grooming business"}],products:[{id:"p1",name:"Dog Grooming Towel",category:"dog grooming",description:"grooming towel",url:"https://bingodogwash.com/shop"}]});assert.equal(result.partial,true);assert.equal(result.prospectsQueued,0);assert.equal(result.searchApiCost,0);});

test("completed nightly retry is idempotent",async()=>{const existing={id:"run-1",status:"completed",prospects_queued:2};const db=recordingDb({existingRun:existing});const result=await runProspecting({GIFT_CARD_DB:db},{trigger:"scheduled",now:"2026-08-11T02:00:00.000Z"});assert.equal(result.idempotent,true);assert.equal(result.run,existing);assert.equal(db.calls.some(c=>c.type==="run"),false);});

test("retention job purges dependent data and only expired untouched prospects",async()=>{const db=recordingDb({changes:3});const result=await purgeExpiredProspects(db,"2026-08-11T03:30:00.000Z");assert.equal(result.purged,3);assert.equal(db.calls.filter(c=>c.type==="run").length,4);assert.ok(db.calls.every(c=>/converted_at IS NULL AND last_contacted_at IS NULL/.test(c.sql)));});

test("disabled schedule performs no source or email work",async()=>{const db=recordingDb();const oldFetch=globalThis.fetch;let requests=0;globalThis.fetch=async()=>{requests+=1;return Response.json({});};try{const result=await runProspectingSchedule({cron:prospectingTestHelpers.NIGHTLY_CRON,scheduledTime:Date.now()},{GIFT_CARD_DB:db,AI_PROSPECTING_ENABLED:"false",AI_EMAIL_SENDING_ENABLED:"false"});assert.equal(result.skipped,true);assert.equal(requests,0);assert.equal(db.calls.length,0);}finally{globalThis.fetch=oldFetch;}});

test("scheduled catalogue loading retains Worker env context for provider reads",async()=>{const db=recordingDb();const pending=[];const oldFetch=globalThis.fetch;let credentialBody="";let emailRequests=0;globalThis.fetch=async(url,options={})=>{const target=String(url);if(target.includes("auth")||target.includes("token")){credentialBody=String(options.body||"");return Response.json({access_token:"scheduled-test-token"});}if(target.includes("product")){return Response.json([{id:"scheduled-product",name:"Dog Grooming Towel",description:"Absorbent grooming towel",price:10,stock:2}]);}if(target.includes("brevo")||target.includes("resend")){emailRequests+=1;}return Response.json({products:[]});};try{await worker.scheduled({cron:prospectingTestHelpers.NIGHTLY_CRON,scheduledTime:Date.parse("2026-08-17T02:00:00.000Z")},{GIFT_CARD_DB:db,AI_PROSPECTING_ENABLED:"true",AI_EMAIL_SENDING_ENABLED:"false",AVASAM_CONSUMER_KEY:"scheduled-consumer",AVASAM_SECRET_KEY:"scheduled-secret",ETSY_FEATURE_ENABLED:"false",ETSY_SYNC_ENABLED:"false"},{waitUntil(promise){pending.push(Promise.resolve(promise));}});await Promise.all(pending);assert.match(credentialBody,/scheduled-consumer/);assert.match(credentialBody,/scheduled-secret/);assert.equal(emailRequests,0);}finally{globalThis.fetch=oldFetch;}});

test("sending remains blocked without the send flag even after approval",async()=>{const db=recordingDb({message:{id:"m1",provider:"brevo",status:"approved",compliance_status:"eligible",email:"info@dogs.test",domain:"dogs.test",subscriber_type:"corporate",lia_basis_recorded:1,consent_recorded:0}});const response=await handleProspectingRequest(req("/messages/m1/send",{method:"POST",body:"{}"}),{ADMIN_API_TOKEN:"admin-token",GIFT_CARD_DB:db,AI_EMAIL_SENDING_ENABLED:"false"});assert.equal(response.status,409);assert.equal((await response.json()).error,"Email sending is disabled.");});

test("suppression is checked before drafting and again before queueing",async()=>{const candidate={business_name:"Dog Grooming Ltd",business_type:"dog groomer",email:"info@dogs.test",subscriber_type:"corporate",lia_basis_recorded:true,source:"companies_house",source_url:"https://find-and-update.company-information.service.gov.uk/company/1",evidence:"dog grooming business"};const product={id:"p1",name:"Dog Grooming Towel",category:"dog grooming",description:"grooming towel",url:"https://bingodogwash.com/shop"};const draftBlocked=await runProspecting({GIFT_CARD_DB:recordingDb({suppressed:true}),AI_PROSPECTING_MIN_SCORE:"35"},{trigger:"manual",now:"2026-08-12T00:00:00.000Z",candidates:[candidate],products:[product]});assert.equal(draftBlocked.blocked,1);const queueDb=recordingDb({suppressionSequence:[false,true]});const queueBlocked=await runProspecting({GIFT_CARD_DB:queueDb,AI_PROSPECTING_MIN_SCORE:"35",AI:{run:async()=>({response:JSON.stringify({subject:"Relevant towel",body:"Source-backed outreach"})})}},{trigger:"manual",now:"2026-08-13T00:00:00.000Z",candidates:[candidate],products:[product]});assert.equal(queueBlocked.blocked,1);assert.equal(queueBlocked.prospectsQueued,0);});

test("Brevo provider failure is isolated and records no social-channel writes",async()=>{const db=recordingDb({message:{id:"m1",provider:"brevo",status:"approved",compliance_status:"eligible",email:"info@dogs.test",domain:"dogs.test",subscriber_type:"corporate",lia_basis_recorded:1,consent_recorded:0}});const oldFetch=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls+=1;return calls===1?Response.json({}, {status:201}):Response.json({message:"rejected"},{status:500});};try{const response=await handleProspectingRequest(req("/messages/m1/send",{method:"POST",body:"{}"}),{ADMIN_API_TOKEN:"admin-token",GIFT_CARD_DB:db,AI_EMAIL_SENDING_ENABLED:"true",AI_EMAIL_CAMPAIGN_PROVIDER:"brevo",BREVO_API_KEY:"private",BREVO_OUTREACH_TEMPLATE_ID:"12",BREVO_OUTREACH_LIST_ID:"34",AI_EMAIL_SENDER_EMAIL:"campaigns@bingodogwash.com",AI_EMAIL_SENDER_NAME:"Bingo Dog Wash"});assert.equal(response.status,502);const body=await response.json();assert.equal(body.provider,"brevo");assert.match(body.error,/other distribution channels are unaffected/);assert.equal(db.calls.some(call=>/marketing_posts|marketing_platform_results|tiktok/i.test(call.sql)),false);}finally{globalThis.fetch=oldFetch;}});

test("authenticated Brevo suppression webhook is authoritative",async()=>{const db=recordingDb();const unauthorised=await handleBrevoWebhook(new Request("https://bingodogwash.com/api/webhooks/brevo/outreach",{method:"POST",body:"{}"}),{GIFT_CARD_DB:db,BREVO_WEBHOOK_SECRET:"secret"});assert.equal(unauthorised.status,401);const response=await handleBrevoWebhook(new Request("https://bingodogwash.com/api/webhooks/brevo/outreach",{method:"POST",headers:{Authorization:"Bearer secret","Content-Type":"application/json"},body:JSON.stringify({event:"hardBounce",email:"Info@Dogs.test","message-id":"brevo-message"})}),{GIFT_CARD_DB:db,BREVO_WEBHOOK_SECRET:"secret"});assert.equal(response.status,200);assert.equal((await response.json()).suppressed,1);assert.ok(db.calls.some(call=>call.sql.includes("outreach_message_events")&&call.values.includes("hardbounce")));assert.ok(db.calls.some(call=>call.sql.includes("suppression_list")&&call.values.includes("brevo:hardbounce")));assert.ok(db.calls.some(call=>call.sql.includes("status IN ('draft','approved','queued')")));assert.ok(db.calls.some(call=>call.sql.includes("provider='brevo'")&&call.values.includes("brevo-message")));});

test("Brevo webhook isolates malformed payloads and individual batch failures",async()=>{const malformed=await handleBrevoWebhook(new Request("https://bingodogwash.com/api/webhooks/brevo/outreach",{method:"POST",headers:{Authorization:"Bearer secret","Content-Type":"application/json"},body:"{"}),{GIFT_CARD_DB:recordingDb(),BREVO_WEBHOOK_SECRET:"secret"});assert.equal(malformed.status,200);assert.equal((await malformed.json()).invalidPayload,true);const successfulEmails=[];const db={prepare(sql){let values=[];return {bind(...next){values=next;return this;},async run(){if(sql.includes("outreach_message_events")&&values.includes("bad@dogs.test"))throw new Error("row failure");if(sql.includes("suppression_list"))successfulEmails.push(values[1]);return {success:true};}};}};const response=await handleBrevoWebhook(new Request("https://bingodogwash.com/api/webhooks/brevo/outreach",{method:"POST",headers:{Authorization:"Bearer secret","Content-Type":"application/json"},body:JSON.stringify([{event:"spam",email:"bad@dogs.test"},{event:"unsubscribed",email:"good@dogs.test"}])}),{GIFT_CARD_DB:db,BREVO_WEBHOOK_SECRET:"secret"});const result=await response.json();assert.equal(response.status,200);assert.equal(result.failed,1);assert.equal(result.suppressed,1);assert.deepEqual(successfulEmails,["good@dogs.test"]);});

test("schema and scheduler preserve explicit compliance and never schedule sending",()=>{const migration=readFileSync(new URL("../migrations/0016_ai_customer_finder.sql",import.meta.url),"utf8");const worker=readFileSync(new URL("../_functions_NOT_FOR_STATIC_UPLOAD/api/worker.js",import.meta.url),"utf8");assert.match(migration,/subscriber_type TEXT NOT NULL DEFAULT 'unknown'/);assert.match(migration,/lia_basis_recorded INTEGER NOT NULL DEFAULT 0/);assert.match(migration,/search_api_cost REAL NOT NULL/);assert.match(migration,/provider TEXT NOT NULL DEFAULT 'brevo'/);const scheduled=worker.slice(worker.indexOf("async scheduled("),worker.indexOf("async function handleRequestWithAssets"));assert.match(scheduled,/runProspectingSchedule/);assert.doesNotMatch(scheduled,/EMAIL\.send|api\.brevo|api\.resend/);});
