import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { handleBrevoWebhook, handleProspectingRequest, purgeExpiredProspects, runProspecting, runProspectingSchedule, prospectingTestHelpers } from "../_functions_NOT_FOR_STATIC_UPLOAD/api/prospecting.js";

const auth={Authorization:"Bearer admin-token","Content-Type":"application/json"};
const req=(path="",options={})=>new Request(`https://admin.bingodogwash.com/api/admin/prospecting${path}`,{headers:{...auth,...options.headers},...options});

function recordingDb(options={}){const calls=[];return {calls,prepare(sql){let values=[];return {bind(...next){values=next;return this;},async first(){calls.push({sql,values,type:"first"});if(sql.includes("outreach_runs WHERE idempotency_key"))return options.existingRun||null;if(sql.includes("outreach_messages o JOIN prospects"))return options.message||null;if(sql.includes("suppression_list")){const blocked=options.suppressionSequence?.length?options.suppressionSequence.shift():options.suppressed;return blocked?{blocked:1}:null;}return null;},async all(){calls.push({sql,values,type:"all"});return {results:[]};},async run(){calls.push({sql,values,type:"run"});return {success:true,meta:{changes:options.changes??1}};}};}};}

test("prospecting endpoints require admin authorisation",async()=>{const response=await handleProspectingRequest(new Request("https://admin.bingodogwash.com/api/admin/prospecting"),{ADMIN_API_TOKEN:"admin-token"});assert.equal(response.status,401);});

test("manual prospecting is blocked while the feature flag is false",async()=>{const response=await handleProspectingRequest(req("/run",{method:"POST",body:"{}"}),{ADMIN_API_TOKEN:"admin-token",GIFT_CARD_DB:recordingDb(),AI_PROSPECTING_ENABLED:"false"});assert.equal(response.status,409);});

test("subscriber type and LIA gates fail closed",()=>{const gate=prospectingTestHelpers.complianceFor;assert.equal(gate({email:"info@limited.test",subscriber_type:"corporate",lia_basis_recorded:false}),"lia_required");assert.equal(gate({email:"owner@sole.test",subscriber_type:"individual",lia_basis_recorded:true,consent_recorded:false}),"pecr_consent_required");assert.equal(gate({email:"hello@unknown.test",subscriber_type:"unknown",lia_basis_recorded:true,consent_recorded:false}),"pecr_consent_required");assert.equal(gate({email:"info@limited.test",subscriber_type:"corporate",lia_basis_recorded:true}),"eligible");});

test("normalisation populates subscriber type, LIA and retention for every prospect",()=>{const p=prospectingTestHelpers.normaliseProspect({business_name:"Dog Grooming Ltd",business_type:"dog groomer",email:"info@dogs.test",subscriber_type:"corporate",lia_basis_recorded:true,source:"companies_house",source_url:"https://find-and-update.company-information.service.gov.uk/company/1",evidence:"Active limited company"},"2026-08-11T00:00:00.000Z");assert.equal(p.subscriber_type,"corporate");assert.equal(p.lia_basis_recorded,true);assert.equal(p.source_date,"2026-08-11");assert.equal(p.retention_expires_at,"2027-08-11T00:00:00.000Z");});

test("cost cap aborts cleanly before AI drafting",async()=>{const db=recordingDb();const result=await runProspecting({GIFT_CARD_DB:db,AI_PROSPECTING_MAX_COST_GBP:"0",AI_PROSPECTING_AI_ESTIMATED_COST_GBP:"0.01",AI_PROSPECTING_MIN_SCORE:"35"},{trigger:"manual",now:"2026-08-11T00:00:00.000Z",candidates:[{business_name:"Dog Grooming Ltd",business_type:"dog groomer",email:"info@dogs.test",subscriber_type:"corporate",lia_basis_recorded:true,source:"companies_house",source_url:"https://find-and-update.company-information.service.gov.uk/company/1",evidence:"dog grooming business"}],products:[{id:"p1",name:"Dog Grooming Towel",category:"dog grooming",description:"grooming towel",url:"https://bingodogwash.com/shop"}]});assert.equal(result.partial,true);assert.equal(result.prospectsQueued,0);assert.equal(result.searchApiCost,0);});

test("completed nightly retry is idempotent",async()=>{const existing={id:"run-1",status:"completed",prospects_queued:2};const db=recordingDb({existingRun:existing});const result=await runProspecting({GIFT_CARD_DB:db},{trigger:"scheduled",now:"2026-08-11T02:00:00.000Z"});assert.equal(result.idempotent,true);assert.equal(result.run,existing);assert.equal(db.calls.some(c=>c.type==="run"),false);});

test("retention job purges dependent data and only expired untouched prospects",async()=>{const db=recordingDb({changes:3});const result=await purgeExpiredProspects(db,"2026-08-11T03:30:00.000Z");assert.equal(result.purged,3);assert.equal(db.calls.filter(c=>c.type==="run").length,4);assert.ok(db.calls.every(c=>/converted_at IS NULL AND last_contacted_at IS NULL/.test(c.sql)));});

test("disabled schedule performs no source or email work",async()=>{const db=recordingDb();const oldFetch=globalThis.fetch;let requests=0;globalThis.fetch=async()=>{requests+=1;return Response.json({});};try{const result=await runProspectingSchedule({cron:prospectingTestHelpers.NIGHTLY_CRON,scheduledTime:Date.now()},{GIFT_CARD_DB:db,AI_PROSPECTING_ENABLED:"false",AI_EMAIL_SENDING_ENABLED:"false"});assert.equal(result.skipped,true);assert.equal(requests,0);assert.equal(db.calls.length,0);}finally{globalThis.fetch=oldFetch;}});

test("sending remains blocked without the send flag even after approval",async()=>{const db=recordingDb({message:{id:"m1",provider:"brevo",status:"approved",compliance_status:"eligible",email:"info@dogs.test",domain:"dogs.test",subscriber_type:"corporate",lia_basis_recorded:1,consent_recorded:0}});const response=await handleProspectingRequest(req("/messages/m1/send",{method:"POST",body:"{}"}),{ADMIN_API_TOKEN:"admin-token",GIFT_CARD_DB:db,AI_EMAIL_SENDING_ENABLED:"false"});assert.equal(response.status,409);assert.equal((await response.json()).error,"Email sending is disabled.");});

test("suppression is checked before drafting and again before queueing",async()=>{const candidate={business_name:"Dog Grooming Ltd",business_type:"dog groomer",email:"info@dogs.test",subscriber_type:"corporate",lia_basis_recorded:true,source:"companies_house",source_url:"https://find-and-update.company-information.service.gov.uk/company/1",evidence:"dog grooming business"};const product={id:"p1",name:"Dog Grooming Towel",category:"dog grooming",description:"grooming towel",url:"https://bingodogwash.com/shop"};const draftBlocked=await runProspecting({GIFT_CARD_DB:recordingDb({suppressed:true}),AI_PROSPECTING_MIN_SCORE:"35"},{trigger:"manual",now:"2026-08-12T00:00:00.000Z",candidates:[candidate],products:[product]});assert.equal(draftBlocked.blocked,1);const queueDb=recordingDb({suppressionSequence:[false,true]});const queueBlocked=await runProspecting({GIFT_CARD_DB:queueDb,AI_PROSPECTING_MIN_SCORE:"35",AI:{run:async()=>({response:JSON.stringify({subject:"Relevant towel",body:"Source-backed outreach"})})}},{trigger:"manual",now:"2026-08-13T00:00:00.000Z",candidates:[candidate],products:[product]});assert.equal(queueBlocked.blocked,1);assert.equal(queueBlocked.prospectsQueued,0);});

test("Brevo provider failure is isolated and records no social-channel writes",async()=>{const db=recordingDb({message:{id:"m1",provider:"brevo",status:"approved",compliance_status:"eligible",email:"info@dogs.test",domain:"dogs.test",subscriber_type:"corporate",lia_basis_recorded:1,consent_recorded:0}});const oldFetch=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls+=1;return calls===1?Response.json({}, {status:201}):Response.json({message:"rejected"},{status:500});};try{const response=await handleProspectingRequest(req("/messages/m1/send",{method:"POST",body:"{}"}),{ADMIN_API_TOKEN:"admin-token",GIFT_CARD_DB:db,AI_EMAIL_SENDING_ENABLED:"true",AI_EMAIL_CAMPAIGN_PROVIDER:"brevo",BREVO_API_KEY:"private",BREVO_OUTREACH_TEMPLATE_ID:"12",BREVO_OUTREACH_LIST_ID:"34",AI_EMAIL_SENDER_EMAIL:"campaigns@bingodogwash.com",AI_EMAIL_SENDER_NAME:"Bingo Dog Wash"});assert.equal(response.status,502);const body=await response.json();assert.equal(body.provider,"brevo");assert.match(body.error,/other distribution channels are unaffected/);assert.equal(db.calls.some(call=>/marketing_posts|marketing_platform_results|tiktok/i.test(call.sql)),false);}finally{globalThis.fetch=oldFetch;}});

test("authenticated Brevo suppression webhook is authoritative",async()=>{const db=recordingDb();const unauthorised=await handleBrevoWebhook(new Request("https://bingodogwash.com/api/webhooks/brevo/outreach",{method:"POST",body:"{}"}),{GIFT_CARD_DB:db,BREVO_WEBHOOK_SECRET:"secret"});assert.equal(unauthorised.status,401);const response=await handleBrevoWebhook(new Request("https://bingodogwash.com/api/webhooks/brevo/outreach",{method:"POST",headers:{Authorization:"Bearer secret","Content-Type":"application/json"},body:JSON.stringify({event:"hardBounce",email:"Info@Dogs.test","message-id":"brevo-message"})}),{GIFT_CARD_DB:db,BREVO_WEBHOOK_SECRET:"secret"});assert.equal(response.status,200);assert.equal((await response.json()).suppressed,1);assert.ok(db.calls.some(call=>call.sql.includes("outreach_message_events")&&call.values.includes("hardbounce")));assert.ok(db.calls.some(call=>call.sql.includes("suppression_list")&&call.values.includes("brevo:hardbounce")));assert.ok(db.calls.some(call=>call.sql.includes("status IN ('draft','approved','queued')")));assert.ok(db.calls.some(call=>call.sql.includes("provider='brevo'")&&call.values.includes("brevo-message")));});

test("Brevo webhook isolates malformed payloads and individual batch failures",async()=>{const malformed=await handleBrevoWebhook(new Request("https://bingodogwash.com/api/webhooks/brevo/outreach",{method:"POST",headers:{Authorization:"Bearer secret","Content-Type":"application/json"},body:"{"}),{GIFT_CARD_DB:recordingDb(),BREVO_WEBHOOK_SECRET:"secret"});assert.equal(malformed.status,200);assert.equal((await malformed.json()).invalidPayload,true);const successfulEmails=[];const db={prepare(sql){let values=[];return {bind(...next){values=next;return this;},async run(){if(sql.includes("outreach_message_events")&&values.includes("bad@dogs.test"))throw new Error("row failure");if(sql.includes("suppression_list"))successfulEmails.push(values[1]);return {success:true};}};}};const response=await handleBrevoWebhook(new Request("https://bingodogwash.com/api/webhooks/brevo/outreach",{method:"POST",headers:{Authorization:"Bearer secret","Content-Type":"application/json"},body:JSON.stringify([{event:"spam",email:"bad@dogs.test"},{event:"unsubscribed",email:"good@dogs.test"}])}),{GIFT_CARD_DB:db,BREVO_WEBHOOK_SECRET:"secret"});const result=await response.json();assert.equal(response.status,200);assert.equal(result.failed,1);assert.equal(result.suppressed,1);assert.deepEqual(successfulEmails,["good@dogs.test"]);});

test("schema and scheduler preserve explicit compliance and never schedule sending",()=>{const migration=readFileSync(new URL("../migrations/0016_ai_customer_finder.sql",import.meta.url),"utf8");const worker=readFileSync(new URL("../_functions_NOT_FOR_STATIC_UPLOAD/api/worker.js",import.meta.url),"utf8");assert.match(migration,/subscriber_type TEXT NOT NULL DEFAULT 'unknown'/);assert.match(migration,/lia_basis_recorded INTEGER NOT NULL DEFAULT 0/);assert.match(migration,/search_api_cost REAL NOT NULL/);assert.match(migration,/provider TEXT NOT NULL DEFAULT 'brevo'/);const scheduled=worker.slice(worker.indexOf("async scheduled("),worker.indexOf("async function handleRequestWithAssets"));assert.match(scheduled,/runProspectingSchedule/);assert.doesNotMatch(scheduled,/EMAIL\.send|api\.brevo|api\.resend/);});
